import { DifficultyTexts } from './data';

export const technicalData: DifficultyTexts = {
    beginner: {
        30: [
            { id: 't_b_30_1', text: "A variable stores data that can be used later. You can name variables anything that describes their purpose." },
            { id: 't_b_30_2', text: "HTML gives structure to web pages. Tags like div, span, and p organize the content on a page." },
            { id: 't_b_30_3', text: "CSS makes websites look nice. You can change colors, fonts, sizes, and spacing with CSS rules." },
            { id: 't_b_30_4', text: "JavaScript makes web pages interactive. It can respond to clicks, show alerts, and change content." },
            { id: 't_b_30_5', text: "A loop repeats code. For loops and while loops help you avoid writing the same thing many times." },
            { id: 't_b_30_6', text: "An array is a list of items stored together. Each item has a position called an index starting from zero." },
            { id: 't_b_30_7', text: "A function is a reusable block of code. It takes input, processes it, and can return a result." },
            { id: 't_b_30_8', text: "Git tracks changes in code. It lets developers save versions and work together on the same project." },
            { id: 't_b_30_9', text: "Debugging means finding and fixing code mistakes. It requires patience, logic, and reading error messages." },
            { id: 't_b_30_10', text: "The internet connects computers worldwide using protocols. HTTP allows browsers to load and display websites." }
        ],
        60: [
            { id: 't_b_60_1', text: "A variable in programming is like a container. It stores data that can be used later. You can name variables anything, but it is best to use names that describe what is inside. Good naming makes code easier to read." },
            { id: 't_b_60_2', text: "The internet is a vast network of computers. They talk to each other using special rules called protocols. The most common protocol is HTTP, which allows you to view websites. HTTPS adds a layer of security to keep data safe." },
            { id: 't_b_60_3', text: "Debugging is the process of finding and fixing mistakes in code. It requires patience and logic. Sometimes the error is just a missing semicolon or a typo. Other times, the bug hides in complex logic that needs careful review." },
            { id: 't_b_60_4', text: "HTML stands for Hyper Text Markup Language. It is used to create the structure of web pages. Tags like head, body, and div help organize the content on a page. HTML works together with CSS and JavaScript to build modern websites." },
            { id: 't_b_60_5', text: "CSS stands for Cascading Style Sheets. It is used to make web pages look nice. You can change colors, fonts, and the layout of a page using CSS rules. Responsive design ensures sites look good on all screen sizes." },
            { id: 't_b_60_6', text: "JavaScript is a popular programming language. It runs inside your web browser and makes websites interactive. You can use it to create buttons, forms, and animations. JavaScript is also used on the server side with Node.js." },
            { id: 't_b_60_7', text: "A loop in programming repeats a block of code. There are different types like for loops and while loops. Loops help you avoid writing the same code over and over again. They are essential for processing lists and collections of data." },
            { id: 't_b_60_8', text: "An array is a list of items stored together. You can store numbers, words, or even other arrays inside it. Each item has a position number called an index starting from zero. Arrays make it easy to organize and process groups of data." },
            { id: 't_b_60_9', text: "A function is a reusable block of code. It takes some input, does something with it, and returns a result. Functions make code easier to read and maintain. They also help avoid repeating the same logic in multiple places." },
            { id: 't_b_60_10', text: "Git is a tool that helps developers track changes in their code. It lets you save versions of your work and go back to an older version if needed. Many teams use Git to work together on projects safely and efficiently." }
        ],
        120: [
            { id: 't_b_120_1', text: "A variable in programming is like a container that holds information. It stores data that can be used later in the program. You can name variables anything you want, but it is best to use clear names that describe what is inside. For example, a variable called userName is better than one called x. There are different types of variables such as strings for text, numbers for math, and booleans for true or false values. Understanding variables is the first step in learning to code, as they are used in every program." },
            { id: 't_b_120_2', text: "The internet is a vast network of computers connected around the world. They communicate using special rules called protocols. The most common protocol is HTTP, which allows your browser to load and display websites. When you type a web address, your computer sends a request to a server, which then sends back the page you asked for. This all happens in just milliseconds. Understanding how the internet works helps you become a better developer and troubleshooter. It also helps you appreciate the complex infrastructure behind every website." },
            { id: 't_b_120_3', text: "Debugging is the process of finding and fixing mistakes in computer code. It is one of the most important skills a developer can have. Sometimes the error is obvious, like a missing semicolon or a typo in a variable name. Other times, the bug is hidden deep in the logic of the program and requires careful step-by-step analysis. Tools like console log statements and browser developer tools can help you track down problems. With practice, debugging becomes faster and more intuitive. Every bug you fix teaches you something new about programming." },
            { id: 't_b_120_4', text: "HTML is the foundation of every website. It provides the structure and content that browsers display to users. Elements like headings, paragraphs, images, and links are all created using HTML tags. Each tag serves a specific purpose and helps organize the page into meaningful sections. HTML works closely with CSS, which controls the visual appearance, and JavaScript, which adds interactivity. Learning HTML is typically the first step for anyone interested in web development. It is straightforward to learn and provides immediate visual results, making it a rewarding starting point for beginners." },
            { id: 't_b_120_5', text: "CSS allows developers to control the visual presentation of web pages. With CSS, you can change colors, fonts, spacing, and the overall layout of a website. One of the most powerful features of CSS is its ability to create responsive designs that adapt to different screen sizes. Media queries let you apply different styles for phones, tablets, and desktops. CSS also supports animations and transitions that make websites feel smooth and dynamic. Flexbox and Grid are modern layout systems that give developers precise control over how elements are positioned on the page." },
            { id: 't_b_120_6', text: "JavaScript is one of the most widely used programming languages in the world. It was originally created to make web pages interactive, but it has since evolved to power servers, mobile apps, and even desktop applications. In the browser, JavaScript can respond to user actions like clicks and keyboard input, update content dynamically, and communicate with servers to fetch data. On the server side, Node.js allows developers to build fast and scalable applications using JavaScript. Its versatility and large community make it an excellent language for both beginners and experienced developers." },
            { id: 't_b_120_7', text: "Loops are one of the fundamental building blocks of programming. They allow you to execute a block of code multiple times without having to write it out repeatedly. A for loop is commonly used when you know how many times you want to iterate. A while loop continues as long as a condition remains true. Loops are essential for tasks like processing every item in an array, searching through data, or performing calculations. It is important to ensure that your loop has a proper exit condition to avoid infinite loops that can crash your program." },
            { id: 't_b_120_8', text: "Arrays are data structures that store ordered collections of items. They can hold numbers, strings, objects, or even other arrays. Each element in an array is assigned an index number starting from zero. This makes it easy to access, update, or remove specific items. Most programming languages provide built-in methods for working with arrays, such as push, pop, map, filter, and reduce. Arrays are used extensively in real-world applications for managing lists of users, products, or any other groupings of data. Mastering arrays is essential for any programmer." },
            { id: 't_b_120_9', text: "Functions are reusable blocks of code that perform a specific task. They accept inputs called parameters, process them, and can return a result. Functions help organize code into logical sections, making programs easier to read, test, and maintain. Instead of writing the same logic multiple times, you can define a function once and call it whenever you need it. Functions can also call other functions, enabling complex behaviors through composition. In modern JavaScript, arrow functions provide a shorter syntax and handle the this keyword differently from traditional function declarations." },
            { id: 't_b_120_10', text: "Git is a version control system that tracks changes to files over time. It allows developers to save snapshots of their code at any point, making it easy to go back to a previous version if something goes wrong. Git also enables collaboration by letting multiple developers work on the same project without overwriting each other's changes. Branches allow developers to work on new features independently before merging them into the main codebase. Platforms like GitHub and GitLab provide hosting for Git repositories and add features like pull requests and issue tracking." }
        ]
    },
    intermediate: {
        30: [
            { id: 't_i_30_1', text: "Object-oriented programming organizes code into objects containing data and methods. Encapsulation, inheritance, and polymorphism are its core pillars." },
            { id: 't_i_30_2', text: "Database normalization reduces redundancy by dividing tables and defining relationships. The first three normal forms are standard practice." },
            { id: 't_i_30_3', text: "RESTful APIs use HTTP methods to perform CRUD operations on resources identified by URIs in a stateless architecture." },
            { id: 't_i_30_4', text: "Choosing the right data structure impacts performance significantly. Arrays, hash maps, and trees each suit different problems." },
            { id: 't_i_30_5', text: "Asynchronous programming prevents blocking the main thread. Promises and async-await are common patterns in JavaScript." },
            { id: 't_i_30_6', text: "Containerization with Docker packages applications and dependencies into portable images that run consistently across environments." },
            { id: 't_i_30_7', text: "The MVC pattern separates concerns into Model, View, and Controller layers for better maintainability and testability." },
            { id: 't_i_30_8', text: "SQL queries use SELECT, INSERT, UPDATE, and DELETE to manage data. Joins combine data from multiple relational tables." },
            { id: 't_i_30_9', text: "Unit tests verify individual components work correctly. Integration tests ensure modules interact properly together." },
            { id: 't_i_30_10', text: "Version control with Git enables branching strategies like GitFlow for parallel feature development and release management." }
        ],
        60: [
            { id: 't_i_60_1', text: "Object-Oriented Programming is a paradigm based on the concept of objects, which can contain data and code. The four main principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. These concepts help in managing complexity in large software systems." },
            { id: 't_i_60_2', text: "In database design, normalization is the process of organizing data to reduce redundancy and improve data integrity. It involves dividing large tables into smaller, less redundant tables and defining relationships between them. The first three normal forms are standard practice in most applications." },
            { id: 't_i_60_3', text: "RESTful APIs follow a set of architectural constraints for building web services. Resources are identified by URIs, and standard HTTP methods like GET, POST, PUT, and DELETE are used for operations. This stateless approach makes APIs scalable and easy to integrate." },
            { id: 't_i_60_4', text: "Data structures are fundamental to efficient software development. Arrays, linked lists, stacks, queues, and hash tables each have unique properties that make them suitable for different tasks. Choosing the right data structure can significantly impact the performance of an application." },
            { id: 't_i_60_5', text: "Version control systems like Git allow teams to collaborate on code without overwriting each other's work. Branching strategies such as GitFlow enable parallel development of features, bug fixes, and releases. Understanding merge conflicts and rebasing is essential for smooth team workflows." },
            { id: 't_i_60_6', text: "The Model-View-Controller pattern separates an application into three interconnected components. The Model manages data and business logic, the View handles the display, and the Controller processes user input. This separation of concerns makes the codebase more modular and testable." },
            { id: 't_i_60_7', text: "Asynchronous programming allows a program to perform tasks without blocking the main thread. In JavaScript, this is achieved through callbacks, promises, and the async-await syntax. Understanding the event loop and how it manages the call stack is crucial for efficient code." },
            { id: 't_i_60_8', text: "Containerization with Docker has revolutionized software deployment. Containers package an application and its dependencies into a single image that runs consistently across environments. This eliminates the problem of code that works on one machine but fails on another." },
            { id: 't_i_60_9', text: "SQL is the standard language for interacting with relational databases. Key operations include SELECT for retrieving data, INSERT for adding records, UPDATE for modifying entries, and DELETE for removing rows. Mastering joins, subqueries, and indexing is vital for performance." },
            { id: 't_i_60_10', text: "Testing is a critical phase of the software development lifecycle. Unit tests verify individual components, integration tests check how modules work together, and end-to-end tests simulate real user scenarios. A comprehensive testing strategy reduces bugs and improves code quality." }
        ],
        120: [
            { id: 't_i_120_1', text: "Object-Oriented Programming is one of the most widely adopted paradigms in modern software development. It organizes code around objects that encapsulate both data and the methods that operate on that data. The four pillars of OOP are encapsulation, which hides internal state; abstraction, which exposes only necessary interfaces; inheritance, which enables code reuse through class hierarchies; and polymorphism, which allows objects to be treated as instances of their parent class. These principles work together to produce code that is modular, maintainable, and scalable for large enterprise applications." },
            { id: 't_i_120_2', text: "Database normalization is a systematic approach to organizing relational database schemas to minimize redundancy and dependency. The process involves decomposing tables into smaller ones and establishing relationships through foreign keys. First normal form eliminates repeating groups by ensuring each column contains atomic values. Second normal form removes partial dependencies on composite keys. Third normal form eliminates transitive dependencies. While higher normal forms exist, most practical applications adhere to the first three. Proper normalization improves data integrity and simplifies maintenance, though denormalization may be applied strategically for read-heavy performance optimization." },
            { id: 't_i_120_3', text: "RESTful API design has become the de facto standard for building web services that are scalable, maintainable, and easy to consume. REST stands for Representational State Transfer, and it leverages the existing HTTP protocol to perform operations on resources identified by URIs. GET requests retrieve data, POST creates new resources, PUT updates existing ones, and DELETE removes them. Key principles include statelessness, uniform interfaces, and layered system architecture. Proper use of HTTP status codes, pagination, filtering, and versioning are essential practices for building robust APIs that serve diverse client applications." },
            { id: 't_i_120_4', text: "Choosing the right data structure is one of the most impactful decisions a developer makes. Arrays provide fast index-based access but slow insertions in the middle. Linked lists offer efficient insertions and deletions but lack random access. Hash tables enable constant-time lookups for key-value pairs but consume more memory. Binary search trees maintain sorted data for efficient searching and range queries. Understanding the time and space complexity trade-offs of each data structure, often expressed using Big O notation, is essential for writing performant code that scales well with increasing data volumes." },
            { id: 't_i_120_5', text: "Version control is indispensable in modern software development. Git, the most popular distributed version control system, allows developers to track every change made to a codebase over time. Branching enables parallel workstreams where features, bug fixes, and experiments can be developed independently without affecting the main branch. Merging combines these workstreams, and rebasing provides a cleaner linear history. Pull requests facilitate code review before changes are integrated. Understanding advanced Git operations such as cherry-picking, stashing, and interactive rebasing is crucial for maintaining a clean, navigable project history in professional settings." },
            { id: 't_i_120_6', text: "The Model-View-Controller architectural pattern has been a cornerstone of software design for decades. The Model layer encapsulates the application's data and business logic, ensuring that domain rules are consistently applied regardless of how data is presented. The View layer is responsible for rendering the user interface and displaying data to the user. The Controller acts as an intermediary, receiving user input, processing it, and updating the Model or View accordingly. This separation of concerns promotes reusability, testability, and team collaboration, as different developers can work on different layers concurrently." },
            { id: 't_i_120_7', text: "Asynchronous programming is essential for building responsive and performant applications. In JavaScript, the single-threaded event loop model means that long-running operations like network requests or file reads can block the entire application if handled synchronously. Callbacks were the original solution but led to deeply nested code known as callback hell. Promises introduced a cleaner chaining syntax, and the async-await keywords provide an even more readable approach that resembles synchronous code. Understanding microtasks, macrotasks, and the event loop's execution order is crucial for debugging timing-related issues and writing efficient non-blocking code." },
            { id: 't_i_120_8', text: "Docker has fundamentally changed how applications are built, shipped, and deployed. A Docker container packages an application along with all its dependencies, libraries, and configuration files into a single portable unit. This ensures that the application runs identically regardless of the underlying host environment, eliminating the notorious works-on-my-machine problem. Docker images are built from Dockerfiles using a layered file system that promotes caching and efficient storage. Container orchestration platforms like Kubernetes extend Docker's capabilities by automating deployment, scaling, load balancing, and self-healing across clusters of machines." },
            { id: 't_i_120_9', text: "SQL remains the dominant language for querying and managing relational databases. Mastering SQL requires understanding not just basic CRUD operations but also advanced concepts like joins, subqueries, window functions, common table expressions, and stored procedures. Query optimization is critical for performance; techniques include proper indexing, analyzing execution plans, and avoiding anti-patterns like SELECT star queries and N plus one problems. Modern database systems also support features like full-text search, JSON columns, and materialized views. A solid grasp of SQL is indispensable for backend developers, data engineers, and anyone working with structured data." },
            { id: 't_i_120_10', text: "Software testing encompasses multiple strategies that work together to ensure application quality and reliability. Unit tests focus on individual functions or methods in isolation, typically using mock objects to simulate dependencies. Integration tests verify that multiple components work correctly together, testing data flow across module boundaries. End-to-end tests simulate real user interactions with the complete application, validating workflows from start to finish. Test-driven development advocates writing tests before implementation code, resulting in better-designed interfaces and higher confidence during refactoring. Continuous integration pipelines automate test execution, providing immediate feedback on code changes." }
        ]
    },
    professional: {
        30: [
            { id: 't_p_30_1', text: "Microservices decompose applications into independently deployable services communicating via APIs and messaging protocols." },
            { id: 't_p_30_2', text: "The CAP theorem states distributed systems can guarantee only two of consistency, availability, and partition tolerance." },
            { id: 't_p_30_3', text: "Kubernetes orchestrates containerized workloads, automating deployment, scaling, and management across computing clusters." },
            { id: 't_p_30_4', text: "Event-driven architecture decouples services through asynchronous message brokers like Kafka for scalable distributed systems." },
            { id: 't_p_30_5', text: "SOLID principles guide object-oriented design toward maintainability by ensuring single responsibility and dependency inversion." },
            { id: 't_p_30_6', text: "GraphQL empowers clients to request exactly the data they need, reducing over-fetching common in REST APIs." },
            { id: 't_p_30_7', text: "CI/CD pipelines automate building, testing, and deploying code, enabling rapid and reliable software delivery." },
            { id: 't_p_30_8', text: "Observability combines metrics, logs, and distributed tracing to diagnose issues in complex production environments." },
            { id: 't_p_30_9', text: "WebSockets provide full-duplex communication over TCP, enabling real-time data transfer for chat and gaming applications." },
            { id: 't_p_30_10', text: "Infrastructure as Code tools like Terraform define cloud resources declaratively, enabling version-controlled reproducible deployments." }
        ],
        60: [
            { id: 't_p_60_1', text: "Microservices architecture structures an application as a collection of loosely coupled services. This approach improves modularity and makes the application easier to understand, develop, and test. However, it also introduces complexity in inter-service communication and distributed data consistency." },
            { id: 't_p_60_2', text: "The CAP theorem states that a distributed data store can only provide two of the following three guarantees: Consistency, Availability, and Partition Tolerance. In the event of a network partition, a system must choose between availability and consistency." },
            { id: 't_p_60_3', text: "Kubernetes automates the deployment, scaling, and management of containerized applications. Its architecture includes the API server, scheduler, and etcd for state management. Understanding pod lifecycle, service discovery, and ingress controllers is essential for production deployments." },
            { id: 't_p_60_4', text: "Event-driven architecture decouples services by using events as the primary communication mechanism. When a state change occurs, an event is published to a message broker like Kafka. Consumers subscribe to relevant events and process them asynchronously, enabling high scalability." },
            { id: 't_p_60_5', text: "The SOLID principles provide guidelines for writing maintainable object-oriented code. Single Responsibility ensures each class has one reason to change. Open-Closed advocates for extending rather than modifying code. Liskov Substitution, Interface Segregation, and Dependency Inversion complete the framework." },
            { id: 't_p_60_6', text: "GraphQL is a query language for APIs that allows clients to request exactly the data they need. Unlike REST, where the server defines the response structure, GraphQL empowers the client to specify the shape and depth of the data returned, reducing over-fetching." },
            { id: 't_p_60_7', text: "Continuous Integration and Continuous Deployment pipelines automate building, testing, and deploying software. CI ensures code changes are automatically tested upon commit, while CD extends this by deploying verified code to production. Tools like GitHub Actions are widely used." },
            { id: 't_p_60_8', text: "Observability in distributed systems encompasses three pillars: metrics, logs, and traces. Metrics provide quantitative measurements of system health. Logs offer detailed event records. Distributed tracing tracks requests across service boundaries. Together, they enable efficient diagnosis." },
            { id: 't_p_60_9', text: "WebSockets provide a full-duplex communication channel over a single TCP connection, enabling real-time data transfer between client and server. Unlike HTTP's request-response model, WebSockets allow both parties to send messages independently, making them ideal for live applications." },
            { id: 't_p_60_10', text: "Infrastructure as Code tools like Terraform and Pulumi allow engineers to define and provision cloud resources using declarative configuration files. This approach enables version control, automated testing, and repeatable deployments while reducing manual configuration errors." }
        ],
        120: [
            { id: 't_p_120_1', text: "Microservices architecture has emerged as the dominant approach for building large-scale distributed systems. By decomposing monolithic applications into independently deployable services, organizations gain the flexibility to develop, test, and scale individual components without affecting the entire system. Each service typically owns its own database and communicates with other services through well-defined APIs or asynchronous message queues. However, this architectural style introduces significant operational complexity, including the challenges of distributed tracing, eventual consistency, network latency, and the need for robust service discovery and circuit breaker patterns to handle failures gracefully." },
            { id: 't_p_120_2', text: "The CAP theorem, formulated by Eric Brewer, is a fundamental principle in distributed systems design. It states that any distributed data store can simultaneously guarantee at most two of three properties: Consistency, meaning all nodes see the same data at the same time; Availability, meaning every request receives a response; and Partition Tolerance, meaning the system continues to operate despite network failures between nodes. Since network partitions are inevitable in real-world systems, architects must choose between consistency and availability during partition events. This trade-off has led to the development of various consistency models, including eventual consistency and conflict-free replicated data types." },
            { id: 't_p_120_3', text: "Kubernetes has become the industry standard for container orchestration, enabling organizations to manage complex containerized workloads at scale. Its declarative configuration model allows engineers to specify the desired state of their applications, and the Kubernetes control plane works continuously to reconcile the actual state with the desired state. Key concepts include pods as the smallest deployable units, services for stable network endpoints, deployments for declarative updates, and namespaces for resource isolation. Advanced features like horizontal pod autoscaling, custom resource definitions, and operators extend Kubernetes' capabilities for domain-specific automation and sophisticated deployment strategies." },
            { id: 't_p_120_4', text: "Event-driven architecture represents a paradigm shift from traditional request-response communication patterns. In this model, services communicate by producing and consuming events through message brokers such as Apache Kafka, RabbitMQ, or AWS EventBridge. When a significant state change occurs in one service, it publishes an event that other services can subscribe to and process asynchronously. This loose coupling enables independent scalability, improved fault tolerance, and better separation of concerns. Event sourcing, a related pattern, stores the complete history of state changes as an immutable sequence of events, enabling temporal queries and complete audit trails." },
            { id: 't_p_120_5', text: "The SOLID principles represent five fundamental guidelines for writing clean, maintainable, and extensible object-oriented software. The Single Responsibility Principle states that each class should have exactly one reason to change, promoting focused and cohesive designs. The Open-Closed Principle advocates for code that is open for extension but closed for modification, typically achieved through polymorphism and abstraction. Liskov Substitution ensures that subtypes can replace their base types without altering program correctness. Interface Segregation favors many specific interfaces over one general-purpose interface. Dependency Inversion dictates that high-level modules should depend on abstractions rather than concrete implementations." },
            { id: 't_p_120_6', text: "GraphQL has emerged as a powerful alternative to REST for building flexible and efficient APIs. Developed by Facebook, it allows clients to define precisely the structure and depth of the data they need in a single request, eliminating the over-fetching and under-fetching problems common with REST endpoints. The strongly typed schema serves as both documentation and a contract between client and server. Features like subscriptions enable real-time data delivery over WebSockets, while fragments and directives provide mechanisms for query composition and conditional inclusion. Server-side implementations must carefully manage resolver complexity and implement strategies like DataLoader to avoid the N plus one query problem." },
            { id: 't_p_120_7', text: "Continuous Integration and Continuous Deployment form the backbone of modern software delivery practices. CI automates the process of building and testing code every time a developer pushes changes to the repository, catching integration issues early and maintaining a consistently stable codebase. CD extends this automation by deploying verified code to staging or production environments with minimal manual intervention. Pipeline configurations typically include stages for linting, unit testing, integration testing, security scanning, and artifact publishing. Deployment strategies such as blue-green deployments, canary releases, and feature flags minimize risk and enable rapid rollback when issues are detected." },
            { id: 't_p_120_8', text: "Observability has become a critical discipline for operating reliable distributed systems. Unlike traditional monitoring, which relies on predefined metrics and thresholds, observability focuses on the ability to understand internal system state from external outputs. The three pillars of observability are metrics, which provide quantitative measurements over time; logs, which capture discrete events with contextual detail; and distributed traces, which follow individual requests as they traverse multiple services. Tools like Prometheus for metrics, Elasticsearch for logs, and Jaeger for tracing form a comprehensive observability stack. Service level indicators and objectives provide frameworks for defining and measuring reliability targets." },
            { id: 't_p_120_9', text: "WebSocket technology has become essential for building real-time web applications. Unlike the traditional HTTP request-response model, WebSockets establish a persistent, full-duplex communication channel between client and server over a single TCP connection. This eliminates the overhead of repeated handshakes and enables both parties to send messages independently at any time. Use cases include live chat applications, collaborative editing tools, multiplayer games, financial trading dashboards, and IoT device communication. Implementation considerations include connection management, heartbeat mechanisms for detecting dropped connections, message serialization formats, and scaling strategies using WebSocket-aware load balancers and message broker backends." },
            { id: 't_p_120_10', text: "Infrastructure as Code has transformed how organizations provision and manage their computing resources. By defining infrastructure configurations in version-controlled files using tools like Terraform, Pulumi, or AWS CloudFormation, teams can apply the same software engineering practices to infrastructure that they use for application code. This includes code review through pull requests, automated testing of configurations, and reproducible deployments across multiple environments. Declarative approaches specify the desired end state and let the tool determine the necessary changes, while imperative approaches define explicit steps. State management, drift detection, and modular composition through reusable modules are key concepts for managing infrastructure at scale." }
        ]
    }
};
