import { DifficultyTexts } from './data';

export const codeData: DifficultyTexts = {
    beginner: {
        30: [
            { id: 'c_b_30_1', text: "let name = 'Alice'; let age = 25; console.log(name + ' is ' + age + ' years old.');" },
            { id: 'c_b_30_2', text: "function greet(person) { return 'Hello, ' + person + '!'; } console.log(greet('Bob'));" },
            { id: 'c_b_30_3', text: "for (let i = 0; i < 5; i++) { console.log('Count: ' + i); }" },
            { id: 'c_b_30_4', text: "let x = 10; let y = 20; let sum = x + y; console.log('Sum: ' + sum);" },
            { id: 'c_b_30_5', text: "const colors = ['red', 'green', 'blue']; colors.push('yellow'); console.log(colors);" },
            { id: 'c_b_30_6', text: "if (temperature > 30) { console.log('Hot'); } else { console.log('Cool'); }" },
            { id: 'c_b_30_7', text: "function add(a, b) { return a + b; } let result = add(5, 3); console.log(result);" },
            { id: 'c_b_30_8', text: "let user = { name: 'Charlie', age: 28 }; console.log(user.name + ' is ' + user.age);" },
            { id: 'c_b_30_9', text: "let count = 0; while (count < 5) { console.log(count); count++; }" },
            { id: 'c_b_30_10', text: "const PI = 3.14; let radius = 7; let area = PI * radius * radius; console.log(area);" }
        ],
        60: [
            { id: 'c_b_60_1', text: "let name = 'Alice'; let age = 25; console.log(name + ' is ' + age + ' years old.'); let isStudent = true; if (isStudent) { console.log(name + ' is a student.'); }" },
            { id: 'c_b_60_2', text: "function greet(person) { return 'Hello, ' + person + '!'; } let message = greet('Bob'); console.log(message); let numbers = [1, 2, 3, 4, 5]; console.log(numbers.length);" },
            { id: 'c_b_60_3', text: "for (let i = 0; i < 10; i++) { console.log('Count: ' + i); } let fruits = ['apple', 'banana', 'cherry']; fruits.forEach(function(fruit) { console.log(fruit); });" },
            { id: 'c_b_60_4', text: "let x = 10; let y = 20; let sum = x + y; let product = x * y; console.log('Sum: ' + sum); console.log('Product: ' + product); let isGreater = x > y; console.log(isGreater);" },
            { id: 'c_b_60_5', text: "const colors = ['red', 'green', 'blue']; colors.push('yellow'); console.log(colors); let first = colors[0]; let last = colors[colors.length - 1]; console.log(first, last);" },
            { id: 'c_b_60_6', text: "let temperature = 30; if (temperature > 35) { console.log('It is hot.'); } else if (temperature > 20) { console.log('It is warm.'); } else { console.log('It is cold.'); }" },
            { id: 'c_b_60_7', text: "function add(a, b) { return a + b; } function subtract(a, b) { return a - b; } let result = add(5, 3); console.log('5 + 3 = ' + result); result = subtract(10, 4); console.log('10 - 4 = ' + result);" },
            { id: 'c_b_60_8', text: "let user = { name: 'Charlie', age: 28, city: 'London' }; console.log(user.name); console.log(user.age); user.email = 'charlie@example.com'; console.log(user);" },
            { id: 'c_b_60_9', text: "let count = 0; while (count < 5) { console.log('Step ' + count); count++; } console.log('Loop finished. Final count: ' + count);" },
            { id: 'c_b_60_10', text: "const PI = 3.14159; let radius = 7; let area = PI * radius * radius; let circumference = 2 * PI * radius; console.log('Area: ' + area.toFixed(2)); console.log('Circumference: ' + circumference.toFixed(2));" }
        ],
        120: [
            { id: 'c_b_120_1', text: "let name = 'Alice'; let age = 25; let city = 'New York'; console.log(name + ' is ' + age + ' years old and lives in ' + city + '.'); let isStudent = true; if (isStudent) { console.log(name + ' is currently a student.'); } else { console.log(name + ' is not a student.'); } let hobbies = ['reading', 'coding', 'gaming']; console.log('Hobbies: ' + hobbies.join(', ')); for (let i = 0; i < hobbies.length; i++) { console.log('Hobby ' + (i + 1) + ': ' + hobbies[i]); }" },
            { id: 'c_b_120_2', text: "function greet(person) { return 'Hello, ' + person + '!'; } function farewell(person) { return 'Goodbye, ' + person + '. See you soon!'; } let people = ['Alice', 'Bob', 'Charlie', 'Diana']; for (let i = 0; i < people.length; i++) { console.log(greet(people[i])); } console.log('---'); for (let i = 0; i < people.length; i++) { console.log(farewell(people[i])); } console.log('Total people greeted: ' + people.length);" },
            { id: 'c_b_120_3', text: "let scores = [85, 92, 78, 95, 88, 76, 90]; let total = 0; for (let i = 0; i < scores.length; i++) { total += scores[i]; } let average = total / scores.length; console.log('Total score: ' + total); console.log('Average score: ' + average.toFixed(1)); let highest = Math.max(...scores); let lowest = Math.min(...scores); console.log('Highest: ' + highest); console.log('Lowest: ' + lowest); if (average >= 80) { console.log('Grade: A'); } else { console.log('Grade: B'); }" },
            { id: 'c_b_120_4', text: "let todo = []; function addTask(task) { todo.push(task); console.log('Added: ' + task); } function removeTask(index) { let removed = todo.splice(index, 1); console.log('Removed: ' + removed); } function showTasks() { console.log('Your tasks:'); for (let i = 0; i < todo.length; i++) { console.log((i + 1) + '. ' + todo[i]); } } addTask('Buy groceries'); addTask('Clean the house'); addTask('Study JavaScript'); showTasks(); removeTask(1); showTasks();" },
            { id: 'c_b_120_5', text: "let students = [ { name: 'Alice', grade: 90 }, { name: 'Bob', grade: 85 }, { name: 'Charlie', grade: 92 }, { name: 'Diana', grade: 78 } ]; console.log('Student Report:'); for (let i = 0; i < students.length; i++) { let status = students[i].grade >= 80 ? 'Pass' : 'Fail'; console.log(students[i].name + ': ' + students[i].grade + ' - ' + status); } let passed = students.filter(function(s) { return s.grade >= 80; }); console.log('Students who passed: ' + passed.length);" },
            { id: 'c_b_120_6', text: "function celsiusToFahrenheit(celsius) { return (celsius * 9 / 5) + 32; } function fahrenheitToCelsius(fahrenheit) { return (fahrenheit - 32) * 5 / 9; } let temps = [0, 20, 37, 100]; console.log('Celsius to Fahrenheit:'); for (let i = 0; i < temps.length; i++) { let f = celsiusToFahrenheit(temps[i]); console.log(temps[i] + 'C = ' + f.toFixed(1) + 'F'); } console.log('---'); let fTemps = [32, 68, 98.6, 212]; for (let i = 0; i < fTemps.length; i++) { let c = fahrenheitToCelsius(fTemps[i]); console.log(fTemps[i] + 'F = ' + c.toFixed(1) + 'C'); }" },
            { id: 'c_b_120_7', text: "let inventory = { apples: 10, bananas: 6, oranges: 8, grapes: 15 }; function addItem(item, quantity) { if (inventory[item]) { inventory[item] += quantity; } else { inventory[item] = quantity; } console.log('Added ' + quantity + ' ' + item); } function removeItem(item, quantity) { if (inventory[item] && inventory[item] >= quantity) { inventory[item] -= quantity; console.log('Removed ' + quantity + ' ' + item); } else { console.log('Not enough ' + item + ' in stock.'); } } addItem('apples', 5); removeItem('bananas', 3); removeItem('grapes', 20); console.log(inventory);" },
            { id: 'c_b_120_8', text: "function isPalindrome(str) { let reversed = str.split('').reverse().join(''); return str === reversed; } let words = ['racecar', 'hello', 'level', 'world', 'madam', 'javascript']; console.log('Palindrome Check:'); for (let i = 0; i < words.length; i++) { let result = isPalindrome(words[i]); console.log(words[i] + ': ' + (result ? 'Yes' : 'No')); } let sentence = 'A man a plan a canal Panama'; let cleaned = sentence.toLowerCase().split(' ').join(''); console.log(cleaned + ': ' + (isPalindrome(cleaned) ? 'Yes' : 'No'));" },
            { id: 'c_b_120_9', text: "function getDay(number) { let days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']; if (number >= 0 && number <= 6) { return days[number]; } return 'Invalid day number'; } for (let i = 0; i <= 6; i++) { console.log('Day ' + i + ': ' + getDay(i)); } let today = new Date(); let dayIndex = today.getDay(); console.log('Today is: ' + getDay(dayIndex)); let tomorrow = (dayIndex + 1) % 7; console.log('Tomorrow will be: ' + getDay(tomorrow));" },
            { id: 'c_b_120_10', text: "let matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]; console.log('Matrix:'); for (let row = 0; row < matrix.length; row++) { let line = ''; for (let col = 0; col < matrix[row].length; col++) { line += matrix[row][col] + ' '; } console.log(line.trim()); } let sum = 0; for (let row = 0; row < matrix.length; row++) { for (let col = 0; col < matrix[row].length; col++) { sum += matrix[row][col]; } } console.log('Sum of all elements: ' + sum); console.log('Center element: ' + matrix[1][1]);" }
        ]
    },
    intermediate: {
        30: [
            { id: 'c_i_30_1', text: "const fetchData = async (url) => { const res = await fetch(url); return res.json(); };" },
            { id: 'c_i_30_2', text: "class Dog extends Animal { constructor(name) { super(name, 'Woof'); } }" },
            { id: 'c_i_30_3', text: "const evens = numbers.filter(n => n % 2 === 0); const sum = numbers.reduce((a, b) => a + b, 0);" },
            { id: 'c_i_30_4', text: "const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };" },
            { id: 'c_i_30_5', text: "app.get('/api/users', (req, res) => { res.json({ users: [] }); });" },
            { id: 'c_i_30_6', text: "const [data, setData] = useState(null); useEffect(() => { fetch('/api').then(r => r.json()).then(setData); }, []);" },
            { id: 'c_i_30_7', text: "function merge(left, right) { const r = []; while (left.length && right.length) r.push(left[0] <= right[0] ? left.shift() : right.shift()); return [...r, ...left, ...right]; }" },
            { id: 'c_i_30_8', text: "router.get('/home', () => 'Welcome'); router.get('/about', () => 'About Us');" },
            { id: 'c_i_30_9', text: "function createCounter(n = 0) { let c = n; return { inc: () => ++c, dec: () => --c, get: () => c }; }" },
            { id: 'c_i_30_10', text: "emitter.on('data', (val) => console.log(val)); emitter.emit('data', 42);" }
        ],
        60: [
            { id: 'c_i_60_1', text: "const fetchData = async (url) => { try { const response = await fetch(url); if (!response.ok) { throw new Error('HTTP error: ' + response.status); } const data = await response.json(); return data; } catch (error) { console.error('Fetch failed:', error.message); } };" },
            { id: 'c_i_60_2', text: "class Animal { constructor(name, sound) { this.name = name; this.sound = sound; } speak() { return this.name + ' says ' + this.sound; } } class Dog extends Animal { constructor(name) { super(name, 'Woof'); } fetch(item) { return this.name + ' fetches the ' + item; } }" },
            { id: 'c_i_60_3', text: "const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; const evens = numbers.filter(n => n % 2 === 0); const doubled = numbers.map(n => n * 2); const sum = numbers.reduce((acc, n) => acc + n, 0); console.log({ evens, doubled, sum });" },
            { id: 'c_i_60_4', text: "function debounce(func, delay) { let timeoutId; return function(...args) { clearTimeout(timeoutId); timeoutId = setTimeout(() => { func.apply(this, args); }, delay); }; } const handleSearch = debounce((query) => { console.log('Searching for:', query); }, 300);" },
            { id: 'c_i_60_5', text: "const express = require('express'); const app = express(); app.use(express.json()); app.get('/api/users', (req, res) => { res.json({ users: [] }); }); app.post('/api/users', (req, res) => { const { name, email } = req.body; res.status(201).json({ name, email }); }); app.listen(3000);" },
            { id: 'c_i_60_6', text: "const [state, setState] = useState({ loading: false, data: null, error: null }); useEffect(() => { setState(prev => ({ ...prev, loading: true })); fetchData('/api/items').then(data => { setState({ loading: false, data, error: null }); }).catch(error => { setState({ loading: false, data: null, error: error.message }); }); }, []);" },
            { id: 'c_i_60_7', text: "function mergeSort(arr) { if (arr.length <= 1) return arr; const mid = Math.floor(arr.length / 2); const left = mergeSort(arr.slice(0, mid)); const right = mergeSort(arr.slice(mid)); return merge(left, right); } function merge(left, right) { const result = []; while (left.length && right.length) { result.push(left[0] <= right[0] ? left.shift() : right.shift()); } return [...result, ...left, ...right]; }" },
            { id: 'c_i_60_8', text: "const router = { routes: {}, get(path, handler) { this.routes[path] = handler; }, resolve(path) { const handler = this.routes[path]; if (handler) { return handler(); } return '404 Not Found'; } }; router.get('/home', () => 'Welcome Home'); router.get('/about', () => 'About Us'); console.log(router.resolve('/home'));" },
            { id: 'c_i_60_9', text: "function createCounter(initial = 0) { let count = initial; return { increment() { return ++count; }, decrement() { return --count; }, getCount() { return count; }, reset() { count = initial; return count; } }; } const counter = createCounter(10); counter.increment(); counter.increment(); console.log(counter.getCount());" },
            { id: 'c_i_60_10', text: "class EventEmitter { constructor() { this.events = {}; } on(event, listener) { if (!this.events[event]) { this.events[event] = []; } this.events[event].push(listener); } emit(event, ...args) { const listeners = this.events[event]; if (listeners) { listeners.forEach(fn => fn(...args)); } } off(event, listener) { this.events[event] = this.events[event]?.filter(fn => fn !== listener); } }" }
        ],
        120: [
            { id: 'c_i_120_1', text: "const fetchData = async (url, options = {}) => { const { retries = 3, timeout = 5000 } = options; for (let attempt = 1; attempt <= retries; attempt++) { try { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); const response = await fetch(url, { signal: controller.signal }); clearTimeout(timer); if (!response.ok) { throw new Error('HTTP error: ' + response.status); } const data = await response.json(); return data; } catch (error) { console.error('Attempt ' + attempt + ' failed:', error.message); if (attempt === retries) throw error; await new Promise(resolve => setTimeout(resolve, 1000 * attempt)); } } };" },
            { id: 'c_i_120_2', text: "class Shape { constructor(name) { this.name = name; } area() { throw new Error('area() must be implemented'); } describe() { return this.name + ' with area ' + this.area().toFixed(2); } } class Circle extends Shape { constructor(radius) { super('Circle'); this.radius = radius; } area() { return Math.PI * this.radius * this.radius; } } class Rectangle extends Shape { constructor(width, height) { super('Rectangle'); this.width = width; this.height = height; } area() { return this.width * this.height; } } const shapes = [new Circle(5), new Rectangle(4, 6), new Circle(3)]; shapes.forEach(s => console.log(s.describe()));" },
            { id: 'c_i_120_3', text: "const data = [ { name: 'Alice', department: 'Engineering', salary: 90000 }, { name: 'Bob', department: 'Marketing', salary: 75000 }, { name: 'Charlie', department: 'Engineering', salary: 95000 }, { name: 'Diana', department: 'Marketing', salary: 80000 }, { name: 'Eve', department: 'Engineering', salary: 88000 } ]; const byDepartment = data.reduce((acc, emp) => { if (!acc[emp.department]) acc[emp.department] = []; acc[emp.department].push(emp); return acc; }, {}); Object.entries(byDepartment).forEach(([dept, employees]) => { const avgSalary = employees.reduce((sum, e) => sum + e.salary, 0) / employees.length; console.log(dept + ': Avg salary $' + avgSalary.toFixed(0) + ' (' + employees.length + ' employees)'); });" },
            { id: 'c_i_120_4', text: "function throttle(func, limit) { let inThrottle = false; let lastArgs = null; return function(...args) { if (!inThrottle) { func.apply(this, args); inThrottle = true; setTimeout(() => { inThrottle = false; if (lastArgs) { func.apply(this, lastArgs); lastArgs = null; } }, limit); } else { lastArgs = args; } }; } const handleScroll = throttle((event) => { console.log('Scroll position:', window.scrollY); console.log('Event type:', event.type); }, 200); window.addEventListener('scroll', handleScroll);" },
            { id: 'c_i_120_5', text: "const express = require('express'); const app = express(); app.use(express.json()); const users = new Map(); let nextId = 1; app.get('/api/users', (req, res) => { const list = Array.from(users.values()); res.json({ users: list, count: list.length }); }); app.get('/api/users/:id', (req, res) => { const user = users.get(Number(req.params.id)); if (!user) return res.status(404).json({ error: 'User not found' }); res.json(user); }); app.post('/api/users', (req, res) => { const { name, email } = req.body; if (!name || !email) return res.status(400).json({ error: 'Name and email required' }); const user = { id: nextId++, name, email, createdAt: new Date() }; users.set(user.id, user); res.status(201).json(user); }); app.listen(3000, () => console.log('Server running on port 3000'));" },
            { id: 'c_i_120_6', text: "function useLocalStorage(key, initialValue) { const [storedValue, setStoredValue] = useState(() => { try { const item = window.localStorage.getItem(key); return item ? JSON.parse(item) : initialValue; } catch (error) { console.error('Error reading localStorage:', error); return initialValue; } }); const setValue = (value) => { try { const valueToStore = value instanceof Function ? value(storedValue) : value; setStoredValue(valueToStore); window.localStorage.setItem(key, JSON.stringify(valueToStore)); } catch (error) { console.error('Error writing localStorage:', error); } }; return [storedValue, setValue]; } const [theme, setTheme] = useLocalStorage('theme', 'dark'); console.log('Current theme:', theme);" },
            { id: 'c_i_120_7', text: "function quickSort(arr, compareFn = (a, b) => a - b) { if (arr.length <= 1) return arr; const pivot = arr[Math.floor(arr.length / 2)]; const left = []; const middle = []; const right = []; for (const element of arr) { const comparison = compareFn(element, pivot); if (comparison < 0) left.push(element); else if (comparison > 0) right.push(element); else middle.push(element); } return [...quickSort(left, compareFn), ...middle, ...quickSort(right, compareFn)]; } const numbers = [38, 27, 43, 3, 9, 82, 10]; console.log('Sorted:', quickSort(numbers)); const words = ['banana', 'apple', 'cherry']; console.log('Sorted:', quickSort(words, (a, b) => a.localeCompare(b)));" },
            { id: 'c_i_120_8', text: "class LinkedList { constructor() { this.head = null; this.size = 0; } append(value) { const node = { value, next: null }; if (!this.head) { this.head = node; } else { let current = this.head; while (current.next) current = current.next; current.next = node; } this.size++; } prepend(value) { this.head = { value, next: this.head }; this.size++; } toArray() { const result = []; let current = this.head; while (current) { result.push(current.value); current = current.next; } return result; } find(value) { let current = this.head; while (current) { if (current.value === value) return current; current = current.next; } return null; } } const list = new LinkedList(); list.append(1); list.append(2); list.prepend(0); console.log(list.toArray());" },
            { id: 'c_i_120_9', text: "class TaskQueue { constructor(concurrency = 3) { this.concurrency = concurrency; this.running = 0; this.queue = []; } add(task) { return new Promise((resolve, reject) => { this.queue.push({ task, resolve, reject }); this.run(); }); } run() { while (this.running < this.concurrency && this.queue.length > 0) { const { task, resolve, reject } = this.queue.shift(); this.running++; task().then(resolve).catch(reject).finally(() => { this.running--; this.run(); }); } } } const queue = new TaskQueue(2); const delay = (ms, val) => new Promise(r => setTimeout(() => r(val), ms)); queue.add(() => delay(1000, 'A')).then(v => console.log('Done:', v)); queue.add(() => delay(500, 'B')).then(v => console.log('Done:', v)); queue.add(() => delay(800, 'C')).then(v => console.log('Done:', v));" },
            { id: 'c_i_120_10', text: "class PubSub { constructor() { this.topics = {}; this.subId = 0; } subscribe(topic, callback) { if (!this.topics[topic]) this.topics[topic] = {}; const id = ++this.subId; this.topics[topic][id] = callback; return { unsubscribe: () => { delete this.topics[topic][id]; if (Object.keys(this.topics[topic]).length === 0) delete this.topics[topic]; } }; } publish(topic, data) { if (!this.topics[topic]) return; Object.values(this.topics[topic]).forEach(callback => { try { callback(data); } catch (error) { console.error('Subscriber error:', error); } }); } getTopics() { return Object.keys(this.topics); } } const bus = new PubSub(); const sub = bus.subscribe('message', data => console.log('Received:', data)); bus.publish('message', { text: 'Hello!' }); sub.unsubscribe();" }
        ]
    },
    professional: {
        30: [
            { id: 'c_p_30_1', text: "type Result<T, E = Error> = { success: true; data: T } | { success: false; error: E };" },
            { id: 'c_p_30_2', text: "const memoize = <T extends (...args: any[]) => any>(fn: T): T => { const cache = new Map(); return ((...args) => { const k = JSON.stringify(args); return cache.has(k) ? cache.get(k) : (cache.set(k, fn(...args)), cache.get(k)); }) as T; };" },
            { id: 'c_p_30_3', text: "async function* paginate<T>(fetch: (c: string | null) => Promise<{ data: T[]; next: string | null }>) { let c: string | null = null; do { const p = await fetch(c); yield p.data; c = p.next; } while (c); }" },
            { id: 'c_p_30_4', text: "class Observable<T> { private subs = new Set<(v: T) => void>(); subscribe(fn: (v: T) => void) { this.subs.add(fn); return () => this.subs.delete(fn); } next(v: T) { this.subs.forEach(fn => fn(v)); } }" },
            { id: 'c_p_30_5', text: "function retry<T>(fn: () => Promise<T>, n = 3, d = 1000): Promise<T> { return fn().catch(e => n <= 1 ? Promise.reject(e) : new Promise(r => setTimeout(r, d)).then(() => retry(fn, n - 1, d * 2))); }" },
            { id: 'c_p_30_6', text: "const store = <S>(init: S) => { let s = init; const ls = new Set<() => void>(); return { get: () => s, set: (f: (p: S) => S) => { s = f(s); ls.forEach(l => l()); }, sub: (l: () => void) => { ls.add(l); return () => ls.delete(l); } }; };" },
            { id: 'c_p_30_7', text: "class LRUCache<K, V> { private m = new Map<K, V>(); constructor(private cap: number) {} get(k: K) { if (!this.m.has(k)) return; const v = this.m.get(k)!; this.m.delete(k); this.m.set(k, v); return v; } put(k: K, v: V) { this.m.has(k) ? this.m.delete(k) : this.m.size >= this.cap && this.m.delete(this.m.keys().next().value!); this.m.set(k, v); } }" },
            { id: 'c_p_30_8', text: "type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P] };" },
            { id: 'c_p_30_9', text: "async function pool<T>(tasks: (() => Promise<T>)[], n: number) { const res: T[] = []; const exec = new Set<Promise<void>>(); for (const [i, t] of tasks.entries()) { const p = t().then(r => { res[i] = r; }).finally(() => exec.delete(p)); exec.add(p); if (exec.size >= n) await Promise.race(exec); } await Promise.all(exec); return res; }" },
            { id: 'c_p_30_10', text: "type Middleware<T> = (ctx: T, next: () => Promise<void>) => Promise<void>; function compose<T>(mw: Middleware<T>[]) { return (ctx: T) => { let i = -1; const d = (n: number): Promise<void> => n <= i ? Promise.reject('next() twice') : (i = n, mw[n] ? Promise.resolve(mw[n](ctx, () => d(n + 1))) : Promise.resolve()); return d(0); }; }" }
        ],
        60: [
            { id: 'c_p_60_1', text: "type Result<T, E = Error> = { success: true; data: T } | { success: false; error: E }; function safeParse<T>(json: string): Result<T> { try { const data = JSON.parse(json) as T; return { success: true, data }; } catch (e) { return { success: false, error: e instanceof Error ? e : new Error(String(e)) }; } }" },
            { id: 'c_p_60_2', text: "const memoize = <T extends (...args: any[]) => any>(fn: T): T => { const cache = new Map<string, ReturnType<T>>(); return ((...args: Parameters<T>): ReturnType<T> => { const key = JSON.stringify(args); if (cache.has(key)) return cache.get(key)!; const result = fn(...args); cache.set(key, result); return result; }) as T; };" },
            { id: 'c_p_60_3', text: "async function* paginate<T>(fetchPage: (cursor: string | null) => Promise<{ data: T[]; next: string | null }>): AsyncGenerator<T[], void, undefined> { let cursor: string | null = null; do { const page = await fetchPage(cursor); yield page.data; cursor = page.next; } while (cursor !== null); }" },
            { id: 'c_p_60_4', text: "class Observable<T> { private subscribers: Set<(value: T) => void> = new Set(); subscribe(fn: (value: T) => void): () => void { this.subscribers.add(fn); return () => this.subscribers.delete(fn); } next(value: T): void { this.subscribers.forEach(fn => fn(value)); } pipe<U>(transform: (value: T) => U): Observable<U> { const derived = new Observable<U>(); this.subscribe(v => derived.next(transform(v))); return derived; } }" },
            { id: 'c_p_60_5', text: "function retry<T>(fn: () => Promise<T>, { maxAttempts = 3, delay = 1000, backoff = 2 } = {}): Promise<T> { return fn().catch(error => { if (maxAttempts <= 1) throw error; return new Promise(resolve => setTimeout(resolve, delay)).then(() => retry(fn, { maxAttempts: maxAttempts - 1, delay: delay * backoff, backoff })); }); }" },
            { id: 'c_p_60_6', text: "const createStore = <S>(initialState: S) => { let state = initialState; const listeners = new Set<() => void>(); return { getState: () => state, setState: (updater: (prev: S) => S) => { state = updater(state); listeners.forEach(fn => fn()); }, subscribe: (fn: () => void) => { listeners.add(fn); return () => listeners.delete(fn); } }; };" },
            { id: 'c_p_60_7', text: "class LRUCache<K, V> { private cache = new Map<K, V>(); constructor(private capacity: number) {} get(key: K): V | undefined { if (!this.cache.has(key)) return undefined; const value = this.cache.get(key)!; this.cache.delete(key); this.cache.set(key, value); return value; } put(key: K, value: V): void { if (this.cache.has(key)) this.cache.delete(key); else if (this.cache.size >= this.capacity) { this.cache.delete(this.cache.keys().next().value!); } this.cache.set(key, value); } }" },
            { id: 'c_p_60_8', text: "type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P]; }; function deepMerge<T extends Record<string, any>>(target: T, source: DeepPartial<T>): T { const result = { ...target }; for (const key in source) { if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) { result[key] = deepMerge(target[key], source[key] as any); } else { (result as any)[key] = source[key]; } } return result; }" },
            { id: 'c_p_60_9', text: "async function pool<T>(tasks: (() => Promise<T>)[], concurrency: number): Promise<T[]> { const results: T[] = []; const executing = new Set<Promise<void>>(); for (const [i, task] of tasks.entries()) { const p = task().then(result => { results[i] = result; }).finally(() => executing.delete(p)); executing.add(p); if (executing.size >= concurrency) { await Promise.race(executing); } } await Promise.all(executing); return results; }" },
            { id: 'c_p_60_10', text: "interface Middleware<T> { (context: T, next: () => Promise<void>): Promise<void>; } function compose<T>(middlewares: Middleware<T>[]): (context: T) => Promise<void> { return function(context: T) { let index = -1; function dispatch(i: number): Promise<void> { if (i <= index) return Promise.reject(new Error('next() called multiple times')); index = i; const fn = middlewares[i]; if (!fn) return Promise.resolve(); return Promise.resolve(fn(context, () => dispatch(i + 1))); } return dispatch(0); }; }" }
        ],
        120: [
            { id: 'c_p_120_1', text: "type Result<T, E = Error> = { success: true; data: T } | { success: false; error: E }; function safeParse<T>(json: string): Result<T> { try { const data = JSON.parse(json) as T; return { success: true, data }; } catch (e) { return { success: false, error: e instanceof Error ? e : new Error(String(e)) }; } } function safeAsync<T>(promise: Promise<T>): Promise<Result<T>> { return promise.then(data => ({ success: true as const, data })).catch(error => ({ success: false as const, error: error instanceof Error ? error : new Error(String(error)) })); } async function processItems<T, R>(items: T[], processor: (item: T) => Promise<R>): Promise<Result<R>[]> { return Promise.all(items.map(item => safeAsync(processor(item)))); }" },
            { id: 'c_p_120_2', text: "function createMemoizedSelector<S, R>(...args: [...((state: S) => any)[], (...results: any[]) => R]): (state: S) => R { const selectors = args.slice(0, -1) as ((state: S) => any)[]; const combiner = args[args.length - 1] as (...results: any[]) => R; let lastArgs: any[] | null = null; let lastResult: R; return (state: S) => { const currentArgs = selectors.map(sel => sel(state)); if (lastArgs && currentArgs.every((arg, i) => arg === lastArgs![i])) { return lastResult; } lastArgs = currentArgs; lastResult = combiner(...currentArgs); return lastResult; }; } const getUsers = (state: any) => state.users; const getFilter = (state: any) => state.filter; const getFilteredUsers = createMemoizedSelector(getUsers, getFilter, (users: any[], filter: string) => users.filter(u => u.name.includes(filter)));" },
            { id: 'c_p_120_3', text: "class AsyncQueue<T> { private queue: T[] = []; private resolvers: ((value: T) => void)[] = []; private closed = false; enqueue(item: T): void { if (this.closed) throw new Error('Queue is closed'); if (this.resolvers.length > 0) { const resolve = this.resolvers.shift()!; resolve(item); } else { this.queue.push(item); } } dequeue(): Promise<T> { if (this.queue.length > 0) { return Promise.resolve(this.queue.shift()!); } if (this.closed) return Promise.reject(new Error('Queue is closed')); return new Promise<T>(resolve => { this.resolvers.push(resolve); }); } close(): void { this.closed = true; this.resolvers.forEach(resolve => { resolve(undefined as any); }); this.resolvers = []; } get size(): number { return this.queue.length; } get pending(): number { return this.resolvers.length; } }" },
            { id: 'c_p_120_4', text: "type Validator<T> = (value: unknown) => value is T; const string = (): Validator<string> => (value: unknown): value is string => typeof value === 'string'; const number = (): Validator<number> => (value: unknown): value is number => typeof value === 'number' && !isNaN(value); const array = <T>(itemValidator: Validator<T>): Validator<T[]> => (value: unknown): value is T[] => Array.isArray(value) && value.every(itemValidator); const object = <T extends Record<string, Validator<any>>>(schema: T): Validator<{ [K in keyof T]: T[K] extends Validator<infer U> ? U : never }> => (value: unknown): value is any => { if (typeof value !== 'object' || value === null) return false; return Object.entries(schema).every(([key, validator]) => validator((value as any)[key])); }; const userValidator = object({ name: string(), age: number(), tags: array(string()) });" },
            { id: 'c_p_120_5', text: "class DependencyContainer { private singletons = new Map<string, any>(); private factories = new Map<string, () => any>(); register<T>(key: string, factory: () => T, singleton = true): void { if (singleton) { this.factories.set(key, () => { if (!this.singletons.has(key)) { this.singletons.set(key, factory()); } return this.singletons.get(key); }); } else { this.factories.set(key, factory); } } resolve<T>(key: string): T { const factory = this.factories.get(key); if (!factory) throw new Error('No registration for: ' + key); return factory(); } has(key: string): boolean { return this.factories.has(key); } clear(): void { this.singletons.clear(); this.factories.clear(); } } const container = new DependencyContainer(); container.register('config', () => ({ apiUrl: 'https://api.example.com', timeout: 5000 })); container.register('logger', () => ({ log: (msg: string) => console.log('[LOG]', msg) })); const config = container.resolve<{ apiUrl: string }>('config');" },
            { id: 'c_p_120_6', text: "type State = Record<string, any>; type Action = { type: string; payload?: any }; type Reducer<S> = (state: S, action: Action) => S; type Middleware<S> = (store: { getState: () => S; dispatch: (action: Action) => void }) => (next: (action: Action) => void) => (action: Action) => void; function createReduxStore<S>(reducer: Reducer<S>, initialState: S, middlewares: Middleware<S>[] = []) { let state = initialState; const listeners = new Set<() => void>(); const getState = () => state; let dispatch: (action: Action) => void = (action) => { state = reducer(state, action); listeners.forEach(fn => fn()); }; const store = { getState, dispatch: (action: Action) => dispatch(action), subscribe: (fn: () => void) => { listeners.add(fn); return () => listeners.delete(fn); } }; dispatch = middlewares.reverse().reduce((next, mw) => mw(store)(next), dispatch); store.dispatch = dispatch; return store; }" },
            { id: 'c_p_120_7', text: "class BinarySearchTree<T> { private root: { value: T; left: any; right: any } | null = null; constructor(private compareFn: (a: T, b: T) => number = (a: any, b: any) => a - b) {} insert(value: T): void { const node = { value, left: null, right: null }; if (!this.root) { this.root = node; return; } let current = this.root; while (true) { if (this.compareFn(value, current.value) < 0) { if (!current.left) { current.left = node; return; } current = current.left; } else { if (!current.right) { current.right = node; return; } current = current.right; } } } find(value: T): boolean { let current = this.root; while (current) { const cmp = this.compareFn(value, current.value); if (cmp === 0) return true; current = cmp < 0 ? current.left : current.right; } return false; } inOrder(): T[] { const result: T[] = []; const traverse = (node: any) => { if (!node) return; traverse(node.left); result.push(node.value); traverse(node.right); }; traverse(this.root); return result; } }" },
            { id: 'c_p_120_8', text: "class CircuitBreaker<T> { private failures = 0; private lastFailureTime = 0; private state: 'closed' | 'open' | 'half-open' = 'closed'; constructor(private fn: () => Promise<T>, private threshold: number = 5, private resetTimeout: number = 30000) {} async execute(): Promise<T> { if (this.state === 'open') { if (Date.now() - this.lastFailureTime > this.resetTimeout) { this.state = 'half-open'; } else { throw new Error('Circuit breaker is open'); } } try { const result = await this.fn(); if (this.state === 'half-open') { this.state = 'closed'; this.failures = 0; } return result; } catch (error) { this.failures++; this.lastFailureTime = Date.now(); if (this.failures >= this.threshold) { this.state = 'open'; } throw error; } } getState(): string { return this.state; } reset(): void { this.state = 'closed'; this.failures = 0; } }" },
            { id: 'c_p_120_9', text: "type EventMap = Record<string, any>; class TypedEventEmitter<Events extends EventMap> { private handlers = new Map<keyof Events, Set<Function>>(); on<K extends keyof Events>(event: K, handler: (payload: Events[K]) => void): () => void { if (!this.handlers.has(event)) { this.handlers.set(event, new Set()); } this.handlers.get(event)!.add(handler); return () => this.handlers.get(event)?.delete(handler); } once<K extends keyof Events>(event: K, handler: (payload: Events[K]) => void): () => void { const wrapper = (payload: Events[K]) => { handler(payload); off(); }; const off = this.on(event, wrapper); return off; } emit<K extends keyof Events>(event: K, payload: Events[K]): void { this.handlers.get(event)?.forEach(handler => { try { handler(payload); } catch (e) { console.error('Event handler error:', e); } }); } removeAllListeners(event?: keyof Events): void { if (event) { this.handlers.delete(event); } else { this.handlers.clear(); } } } interface AppEvents { 'user:login': { userId: string; timestamp: number }; 'user:logout': { userId: string }; 'data:update': { key: string; value: any }; }" },
            { id: 'c_p_120_10', text: "class StreamProcessor<T> { private transforms: ((chunk: T) => T | null)[] = []; private errorHandler: (error: Error, chunk: T) => void = () => {}; filter(predicate: (item: T) => boolean): StreamProcessor<T> { this.transforms.push(chunk => predicate(chunk) ? chunk : null); return this; } map(fn: (item: T) => T): StreamProcessor<T> { this.transforms.push(chunk => fn(chunk)); return this; } onError(handler: (error: Error, chunk: T) => void): StreamProcessor<T> { this.errorHandler = handler; return this; } process(items: T[]): T[] { const results: T[] = []; for (const item of items) { try { let current: T | null = item; for (const transform of this.transforms) { if (current === null) break; current = transform(current); } if (current !== null) results.push(current); } catch (error) { this.errorHandler(error instanceof Error ? error : new Error(String(error)), item); } } return results; } } const processor = new StreamProcessor<{ name: string; value: number }>(); const output = processor.filter(item => item.value > 0).map(item => ({ ...item, value: item.value * 2 })).process([{ name: 'a', value: 5 }, { name: 'b', value: -1 }, { name: 'c', value: 3 }]);" }
        ]
    }
};
