import { DifficultyTexts } from './data';

export const generalData: DifficultyTexts = {
    beginner: {
        30: [
            { id: 'g_b_30_1', text: "The sun rises in the east and sets in the west. Every morning brings a new chance." },
            { id: 'g_b_30_2', text: "Reading is a wonderful habit. It opens doors to new worlds and ideas for everyone." },
            { id: 'g_b_30_3', text: "Music is a universal language. People all over the world enjoy listening to songs." },
            { id: 'g_b_30_4', text: "Cooking your own food is a useful skill. You know what goes into every meal." },
            { id: 'g_b_30_5', text: "Sleep is very important for our bodies. Most people need about eight hours each night." },
            { id: 'g_b_30_6', text: "Exercise helps keep your body fit and strong. Even a short walk can help a lot." },
            { id: 'g_b_30_7', text: "Friendship is one of the best things in life. Good friends support you and make you laugh." },
            { id: 'g_b_30_8', text: "The ocean covers most of the Earth. It is home to millions of different creatures." },
            { id: 'g_b_30_9', text: "Traveling to new places is exciting. You get to see different cultures and try new foods." },
            { id: 'g_b_30_10', text: "A clean room helps you think clearly. Keep things tidy and put them in their proper place." }
        ],
        60: [
            { id: 'g_b_60_1', text: "The sun rises in the east and sets in the west. Every morning brings a new chance to start fresh. Birds sing in the trees, and the world wakes up. It is a beautiful time to be alive and enjoy nature." },
            { id: 'g_b_60_2', text: "Reading is a wonderful habit. It opens doors to new worlds and ideas. When you read a book, you can travel without moving your feet. You can meet characters from the past or the future." },
            { id: 'g_b_60_3', text: "Health is wealth, as the saying goes. Eating fruits and vegetables keeps your body strong. A diverse diet provides the vitamins you need. Drinking water is also very important for your energy." },
            { id: 'g_b_60_4', text: "Music is a universal language. People all over the world enjoy listening to songs. Some like fast music, while others prefer slow tunes. Music can make you happy, calm, or even excited." },
            { id: 'g_b_60_5', text: "Cooking is a useful skill to have. When you cook your own food, you know what goes into it. You can make healthy meals at home. It is also a fun way to spend time with family." },
            { id: 'g_b_60_6', text: "Traveling to new places is exciting. You get to see different cultures and try new foods. Every trip teaches you something new about the world. It is one of the best ways to learn and grow." },
            { id: 'g_b_60_7', text: "Sleep is very important for our bodies. When we sleep, our brain rests and repairs itself. Most people need about eight hours of sleep each night. A good night of rest helps you feel fresh the next day." },
            { id: 'g_b_60_8', text: "Friendship is one of the best things in life. Good friends support you and make you laugh. It is important to be kind and honest with your friends. True friendship lasts a very long time." },
            { id: 'g_b_60_9', text: "Exercise helps keep your body fit and strong. Even a short walk every day can make a big difference. Running, swimming, and cycling are all great activities. Find something you enjoy and make it a habit." },
            { id: 'g_b_60_10', text: "The ocean covers most of the Earth. It is home to millions of different creatures. Fish, whales, and dolphins all live in the sea. We must protect our oceans to keep them clean and healthy." }
        ],
        120: [
            { id: 'g_b_120_1', text: "The sun rises in the east and sets in the west. Every morning brings a new chance to start fresh. Birds sing in the trees, and the world wakes up. It is a beautiful time to be alive and enjoy nature. Many people like to take walks in the morning to feel the fresh air. Watching the sunrise can be a calming and peaceful experience. Nature has a way of making us feel grateful for the simple things in life. Even a few minutes outside can improve your mood for the whole day." },
            { id: 'g_b_120_2', text: "Reading is a wonderful habit. It opens doors to new worlds and ideas. When you read a book, you can travel without moving your feet. You can meet characters from the past or the future. Books teach us many things about history, science, and life. They can make us laugh, cry, or think deeply about the world. Reading before bed can help you relax and fall asleep faster. Whether you prefer fiction or nonfiction, there is always something new to discover in a good book." },
            { id: 'g_b_120_3', text: "Health is wealth, as the saying goes. Eating fruits and vegetables keeps your body strong. A diverse diet provides the vitamins you need. Drinking water is also very important for your energy. Exercise is another key part of staying healthy. Even walking for thirty minutes a day can make a big difference. Getting enough sleep helps your body recover and grow. When you take care of your health, you feel better and can do more things you enjoy every single day." },
            { id: 'g_b_120_4', text: "Music is a universal language. People all over the world enjoy listening to songs. Some like fast music, while others prefer slow tunes. Music can make you happy, calm, or even excited. Many people play instruments like the guitar, piano, or drums. Learning to play music takes practice and patience but it is very rewarding. Songs can bring back special memories and connect us to important moments in our lives. Music is truly one of the greatest gifts of human culture." },
            { id: 'g_b_120_5', text: "Cooking is a useful skill to have. When you cook your own food, you know what goes into it. You can make healthy meals at home. It is also a fun way to spend time with family. Trying new recipes from different countries can expand your taste and knowledge. Cooking teaches you about different ingredients, spices, and techniques. It is a creative activity that brings people together around the table. With practice, anyone can become a good cook and enjoy delicious homemade meals." },
            { id: 'g_b_120_6', text: "Traveling to new places is exciting. You get to see different cultures and try new foods. Every trip teaches you something new about the world. It is one of the best ways to learn and grow. When you travel, you meet new people and hear their stories. You also learn to adapt to new situations and solve problems on the go. Traveling does not have to be expensive. Even visiting a nearby town or park can give you a fresh perspective and break from your daily routine." },
            { id: 'g_b_120_7', text: "Sleep is very important for our bodies. When we sleep, our brain rests and repairs itself. Most people need about eight hours of sleep each night. A good night of rest helps you feel fresh the next day. Without enough sleep, it is hard to focus and be productive. You may feel tired, moody, or forgetful. Creating a bedtime routine can help you sleep better. Try to go to bed at the same time every night and keep your room dark and quiet for the best rest." },
            { id: 'g_b_120_8', text: "Friendship is one of the best things in life. Good friends support you and make you laugh. It is important to be kind and honest with your friends. True friendship lasts a very long time. Friends help each other through difficult moments and celebrate good times together. Making new friends can be scary, but it is worth the effort. Be open, listen carefully, and show interest in others. A strong friendship is built on trust, respect, and the willingness to be there for each other." },
            { id: 'g_b_120_9', text: "Exercise helps keep your body fit and strong. Even a short walk every day can make a big difference. Running, swimming, and cycling are all great activities. Find something you enjoy and make it a habit. Exercise is not only good for your body but also for your mind. It releases chemicals in your brain that make you feel happy and less stressed. You do not need to go to a gym to exercise. Dancing, gardening, or playing a sport with friends counts too." },
            { id: 'g_b_120_10', text: "The ocean covers most of the Earth. It is home to millions of different creatures. Fish, whales, and dolphins all live in the sea. We must protect our oceans to keep them clean and healthy. Pollution, plastic waste, and overfishing are serious problems that harm marine life. Everyone can help by reducing plastic use and cleaning up beaches. The ocean also gives us food, oxygen, and helps regulate the climate. Taking care of our oceans means taking care of our entire planet and future." }
        ]
    },
    intermediate: {
        30: [
            { id: 'g_i_30_1', text: "Technology has transformed communication. Emails replace letters, and video calls connect people across the globe instantly." },
            { id: 'g_i_30_2', text: "Climate change poses a serious threat to ecosystems worldwide. Rising temperatures are causing glaciers to melt rapidly." },
            { id: 'g_i_30_3', text: "Education is the foundation of progress. It equips individuals with skills to contribute meaningfully to society." },
            { id: 'g_i_30_4', text: "The human brain contains billions of neurons forming complex networks. Neuroscience continues to unlock its mysteries." },
            { id: 'g_i_30_5', text: "Renewable energy sources are replacing fossil fuels. Solar and wind power reduce our carbon footprint significantly." },
            { id: 'g_i_30_6', text: "Storytelling has been part of human culture for millennia. It helps us share experiences and build empathy." },
            { id: 'g_i_30_7', text: "Globalization has connected economies and cultures worldwide. It creates opportunities but also poses unique challenges." },
            { id: 'g_i_30_8', text: "Artificial intelligence is reshaping industries at an unprecedented pace. Ethical considerations must guide its development." },
            { id: 'g_i_30_9', text: "Mental health deserves the same attention as physical health. Regular exercise and mindfulness practices can help greatly." },
            { id: 'g_i_30_10', text: "Space exploration continues to capture our imagination. Mars missions and satellite technology are expanding our horizons." }
        ],
        60: [
            { id: 'g_i_60_1', text: "The rapid advancement of technology has transformed the way we communicate. In the past, letters took days to arrive, but now emails are delivered instantly. This shift has not only increased efficiency but also created a global village where information flows freely across borders." },
            { id: 'g_i_60_2', text: "Biodiversity refers to the variety of life on Earth. It includes all living things, from microscopic bacteria to huge whales. Each species plays a role in the ecosystem, and the loss of even one can have a ripple effect on the environment. Protecting our planet is crucial for future generations." },
            { id: 'g_i_60_3', text: "Climate change is one of the most pressing issues of our time. Rising temperatures, melting ice caps, and extreme weather events are all signs of a warming planet. Scientists agree that human activity is a major contributor, and immediate action is needed to reduce carbon emissions." },
            { id: 'g_i_60_4', text: "The history of space exploration is filled with remarkable achievements. From the first satellite launch in 1957 to the moon landing in 1969, humanity has pushed the boundaries of what is possible. Today, private companies are developing reusable rockets, making space more accessible than ever before." },
            { id: 'g_i_60_5', text: "Education is the foundation of a prosperous society. It equips individuals with the knowledge and skills needed to contribute meaningfully to their communities. Access to quality education should be a right, not a privilege, and every effort must be made to close the gap for underserved populations." },
            { id: 'g_i_60_6', text: "The human brain is an incredibly complex organ. It contains approximately 86 billion neurons that communicate through electrical and chemical signals. Neuroscience has made significant progress in understanding how the brain processes information, but there is still much we do not know about consciousness." },
            { id: 'g_i_60_7', text: "Renewable energy sources such as solar, wind, and hydropower are becoming increasingly important. As fossil fuel reserves diminish and their environmental impact becomes clearer, nations around the world are investing heavily in clean energy infrastructure to ensure a sustainable future." },
            { id: 'g_i_60_8', text: "The art of storytelling has been a fundamental part of human culture for thousands of years. From ancient cave paintings to modern cinema, we have always sought ways to share our experiences and emotions. Stories help us understand the world and connect with one another on a deeper level." },
            { id: 'g_i_60_9', text: "Globalization has brought both opportunities and challenges to communities worldwide. While it has facilitated trade, cultural exchange, and technological advancement, it has also led to concerns about inequality, job displacement, and the erosion of local traditions." },
            { id: 'g_i_60_10', text: "The concept of artificial intelligence dates back to the mid-twentieth century, but recent breakthroughs in machine learning have accelerated its development. AI now powers everything from virtual assistants to self-driving cars. Society must address the ethical questions these systems raise." }
        ],
        120: [
            { id: 'g_i_120_1', text: "The rapid advancement of technology has transformed the way we communicate. In the past, letters took days to arrive, but now emails are delivered instantly. This shift has not only increased efficiency but also created a global village where information flows freely across borders. Social media platforms have further accelerated this transformation by giving everyone a voice. However, the spread of misinformation and the erosion of privacy remain significant concerns. As technology continues to evolve, we must find ways to harness its benefits while mitigating its risks for the well-being of society." },
            { id: 'g_i_120_2', text: "Biodiversity is essential for the health of our planet. Every species, from the smallest insect to the largest mammal, plays a vital role in maintaining the balance of ecosystems. Deforestation, pollution, and climate change are driving species to extinction at an alarming rate. Conservation efforts, including protected areas and sustainable agriculture, are critical to reversing this trend. Education and awareness campaigns can also encourage communities to adopt environmentally friendly practices. The future of biodiversity depends on collective action from governments, businesses, and individuals working together for a common goal." },
            { id: 'g_i_120_3', text: "Climate change is reshaping the planet in profound ways. Rising sea levels threaten coastal communities, while extreme weather events are becoming more frequent and severe. Agricultural productivity is declining in many regions due to droughts and unpredictable rainfall patterns. Governments around the world are implementing policies to reduce greenhouse gas emissions, and renewable energy adoption is accelerating. However, the transition to a sustainable economy requires significant investment and cooperation across borders. Every individual can contribute by making conscious choices about energy consumption, transportation, and waste reduction in daily life." },
            { id: 'g_i_120_4', text: "Space exploration has entered a new era of innovation and ambition. Government agencies like NASA and ESA are collaborating with private companies such as SpaceX and Blue Origin to make space travel more accessible. The International Space Station continues to serve as a hub for scientific research in microgravity. Plans for permanent lunar bases and crewed missions to Mars are advancing rapidly. These endeavors not only push the boundaries of human knowledge but also inspire future generations of scientists and engineers. Space technology also has practical applications, including satellite communications and Earth observation." },
            { id: 'g_i_120_5', text: "Quality education is the cornerstone of individual empowerment and societal progress. It enables people to think critically, solve problems, and participate actively in their communities. Unfortunately, millions of children around the world still lack access to basic education due to poverty, conflict, and discrimination. Online learning platforms have emerged as a powerful tool for bridging this gap, offering courses and resources to anyone with an internet connection. However, digital literacy and access to technology remain barriers for many. Addressing these challenges requires a concerted effort from governments, nonprofits, and the private sector." },
            { id: 'g_i_120_6', text: "The human brain remains one of the greatest mysteries of science. Despite decades of research, we are only beginning to understand how it generates consciousness, stores memories, and processes emotions. Advances in brain imaging technology have allowed neuroscientists to observe neural activity in real time, leading to breakthroughs in treating conditions like epilepsy and depression. Artificial neural networks, inspired by the brain's architecture, are powering modern artificial intelligence systems. The convergence of neuroscience and technology holds immense promise for both understanding the human condition and developing next-generation computing systems." },
            { id: 'g_i_120_7', text: "Renewable energy is transforming the global energy landscape. Solar panel costs have dropped dramatically over the past decade, making solar power competitive with fossil fuels in many markets. Wind energy capacity is expanding rapidly, with offshore wind farms becoming a significant source of clean electricity. Battery storage technology is also advancing, addressing the intermittency challenges that have historically limited renewable adoption. Governments are setting ambitious targets for carbon neutrality, and investors are increasingly directing capital toward green initiatives. The transition to clean energy is not just an environmental imperative but also an economic opportunity." },
            { id: 'g_i_120_8', text: "Storytelling has always been central to the human experience. Ancient civilizations used oral traditions to pass down history, values, and knowledge from one generation to the next. The invention of the printing press democratized access to stories, and the advent of cinema and television brought visual narratives to billions. Today, digital platforms and social media have made everyone a potential storyteller. Podcasts, blogs, and short-form video content are reshaping how we consume and share stories. Despite the changes in medium, the core purpose of storytelling remains the same: to connect, inspire, and help us make sense of the world." },
            { id: 'g_i_120_9', text: "Globalization has fundamentally altered the economic and cultural landscape of the modern world. International trade agreements have opened new markets, enabling companies to source materials and sell products across continents. Cultural exchange has enriched societies by introducing diverse perspectives, cuisines, and art forms. However, globalization has also widened the gap between wealthy and developing nations. Workers in certain industries have faced job displacement due to outsourcing and automation. Striking a balance between economic integration and the protection of local communities and traditions is one of the defining challenges of our era." },
            { id: 'g_i_120_10', text: "Artificial intelligence is rapidly becoming one of the most transformative technologies of the twenty-first century. Machine learning algorithms can now diagnose diseases, compose music, and even write code. Self-driving vehicles are being tested on public roads, and AI-powered chatbots handle millions of customer interactions daily. Despite these impressive achievements, concerns about bias, transparency, and job displacement persist. The development of ethical frameworks for AI governance is essential to ensure that these technologies benefit all of humanity. Collaboration between technologists, policymakers, and civil society will be crucial in shaping the future of artificial intelligence." }
        ]
    },
    professional: {
        30: [
            { id: 'g_p_30_1', text: "Neuroplasticity demonstrates that the adult brain can form new neural connections throughout life, enabling recovery and learning." },
            { id: 'g_p_30_2', text: "The Dunning-Kruger effect describes how individuals with limited competence overestimate their abilities, while experts underestimate theirs." },
            { id: 'g_p_30_3', text: "Quantum computing leverages superposition and entanglement to process vast datasets beyond classical computational limits." },
            { id: 'g_p_30_4', text: "Epigenetics reveals that environmental factors can modify gene expression without altering the underlying DNA sequence permanently." },
            { id: 'g_p_30_5', text: "Game theory provides mathematical models for analyzing strategic interactions where outcomes depend on all participants' decisions." },
            { id: 'g_p_30_6', text: "Cognitive dissonance arises when contradictory beliefs create psychological discomfort, often leading to rationalization or behavioral change." },
            { id: 'g_p_30_7', text: "Blockchain technology provides a decentralized, immutable ledger system applicable beyond cryptocurrency to supply chains and voting." },
            { id: 'g_p_30_8', text: "Neuromorphic computing mimics neural architecture at the hardware level to achieve energy-efficient pattern recognition and processing." },
            { id: 'g_p_30_9', text: "Resource scarcity poses geopolitical challenges as diminishing freshwater and arable land intensify diplomatic competition between nations." },
            { id: 'g_p_30_10', text: "The philosophy of determinism argues that all events are causally inevitable, raising profound questions about moral responsibility." }
        ],
        60: [
            { id: 'g_p_60_1', text: "The concept of neuroplasticity challenges the traditional view that the adult brain is static. Research demonstrates that the brain can reorganize itself by forming new neural connections throughout life. This adaptability allows for recovery from injuries and the ability to learn new skills, regardless of age, provided there is sufficient cognitive stimulation." },
            { id: 'g_p_60_2', text: "In the realm of cognitive psychology, the Dunning-Kruger effect describes a cognitive bias where individuals with low ability at a task overestimate their ability. Conversely, experts may underestimate their competence, assuming that tasks easy for them are also easy for others. Understanding this bias is essential for accurate self-assessment." },
            { id: 'g_p_60_3', text: "Quantum computing represents a paradigm shift in computational capability. Unlike classical computers that use binary bits, quantum computers leverage qubits that can exist in superposition, enabling them to process vast amounts of data simultaneously. This technology has the potential to revolutionize cryptography, drug discovery, and climate modeling." },
            { id: 'g_p_60_4', text: "The philosophical debate between determinism and free will has persisted for centuries. Determinists argue that every event is the inevitable result of preceding causes. Libertarians maintain that individuals possess genuine agency. This discourse has profound implications for moral responsibility and justice systems." },
            { id: 'g_p_60_5', text: "Epigenetics studies how environmental factors can alter gene expression without changing the underlying DNA sequence. Lifestyle choices such as diet, exercise, and stress management can leave chemical marks on genes that may be passed down to subsequent generations. This challenges the view that genetic destiny is predetermined." },
            { id: 'g_p_60_6', text: "Game theory provides a mathematical framework for analyzing strategic interactions among rational agents. The Nash equilibrium describes a state where no player can benefit by unilaterally changing their strategy. Applications range from economics and political science to evolutionary biology." },
            { id: 'g_p_60_7', text: "Cognitive dissonance occurs when an individual holds two contradictory beliefs or when their actions conflict with their values. This psychological discomfort often leads to rationalization or behavior change to restore internal consistency. Understanding this mechanism is critical for marketing, persuasion, and behavioral economics." },
            { id: 'g_p_60_8', text: "Blockchain technology, originally developed for cryptocurrency, has far-reaching applications beyond finance. Its decentralized and immutable ledger system can be used for supply chain management, identity verification, and secure voting systems. Scalability concerns and energy consumption remain significant hurdles." },
            { id: 'g_p_60_9', text: "The intersection of neuroscience and artificial intelligence has given rise to neuromorphic computing. By emulating neural networks at the hardware level, these systems promise unprecedented energy efficiency and processing speed for tasks such as pattern recognition and natural language understanding." },
            { id: 'g_p_60_10', text: "Resource scarcity is reshaping geopolitics in the twenty-first century. As freshwater reserves deplete and arable land diminishes due to urbanization and desertification, nations must navigate complex diplomatic landscapes to secure essential resources. Cooperative approaches are essential to avoiding conflict." }
        ],
        120: [
            { id: 'g_p_120_1', text: "The concept of neuroplasticity fundamentally challenges the once-dominant view that the adult brain is a fixed and immutable structure. Groundbreaking research over the past several decades has demonstrated that the brain possesses a remarkable ability to reorganize itself by forming new neural connections throughout the entire lifespan. This adaptive capacity is not merely theoretical; it has been observed in stroke patients who regain lost functions, in musicians who develop enhanced auditory processing, and in bilingual individuals whose brains exhibit structural differences from monolingual counterparts. The implications are profound for education, rehabilitation, and our understanding of human potential." },
            { id: 'g_p_120_2', text: "Quantum computing stands at the frontier of technological innovation, promising computational capabilities that vastly exceed those of classical systems. While traditional computers process information in binary bits representing either zero or one, quantum computers utilize qubits that can exist in a state of superposition, representing both values simultaneously. This property, combined with quantum entanglement and interference, enables quantum machines to solve certain classes of problems exponentially faster than their classical counterparts. Applications in cryptography, pharmaceutical research, optimization problems, and climate modeling are already being explored by leading research institutions and technology companies worldwide." },
            { id: 'g_p_120_3', text: "Epigenetics has emerged as one of the most transformative fields in modern biology, revealing that our genes are not our destiny. Environmental factors such as nutrition, stress, toxin exposure, and even social interactions can leave chemical marks on DNA that alter gene expression without modifying the genetic code itself. These epigenetic modifications can be inherited across generations, meaning that parental experiences can influence the health and development of offspring. This discovery has profound implications for public health, as it suggests that lifestyle interventions could have multigenerational benefits and that many chronic diseases may have epigenetic origins." },
            { id: 'g_p_120_4', text: "The tension between determinism and free will remains one of the most enduring philosophical debates. Hard determinists contend that every thought, action, and event is the inevitable consequence of prior causes stretching back to the beginning of the universe. Compatibilists attempt to reconcile determinism with a notion of freedom by redefining free will as acting in accordance with one's desires without external coercion. Libertarians argue for genuine metaphysical agency that transcends causal chains. Advances in neuroscience have added new dimensions to this debate, as brain imaging studies reveal neural activity preceding conscious awareness of decisions." },
            { id: 'g_p_120_5', text: "The application of game theory extends far beyond abstract mathematics into nearly every domain of human interaction. Originally formulated by John von Neumann and Oskar Morgenstern, it provides rigorous models for understanding competitive and cooperative behavior among rational agents. The Nash equilibrium, developed by John Forbes Nash Jr., identifies stable states in strategic games where no participant benefits from unilateral deviation. Modern applications include auction design, international trade negotiations, evolutionary biology, and network economics. The prisoner's dilemma and its iterated variants continue to offer insights into trust, cooperation, and the emergence of social norms." },
            { id: 'g_p_120_6', text: "Cognitive dissonance theory, first proposed by Leon Festinger in 1957, describes the mental discomfort experienced when an individual simultaneously holds two or more contradictory beliefs, values, or attitudes. This discomfort motivates the individual to reduce the inconsistency through various strategies: changing one of the conflicting beliefs, acquiring new information that resolves the contradiction, or minimizing the importance of the conflict. The theory has been extensively validated across diverse experimental paradigms and has applications in understanding consumer behavior, political attitudes, health-related decision-making, and the psychology of self-justification mechanisms." },
            { id: 'g_p_120_7', text: "Blockchain technology represents a fundamental reimagining of how trust and transparency can be established in digital systems. At its core, a blockchain is a distributed ledger that records transactions across a network of computers in a way that makes retroactive alteration virtually impossible. This property has made it the backbone of cryptocurrencies like Bitcoin and Ethereum. Beyond finance, blockchain applications are being developed for supply chain traceability, digital identity management, intellectual property protection, and decentralized governance. However, challenges including energy consumption, regulatory uncertainty, and scalability limitations continue to shape the trajectory of blockchain adoption." },
            { id: 'g_p_120_8', text: "Neuromorphic computing represents a convergence of neuroscience and semiconductor engineering that seeks to replicate the computational principles of the biological brain in silicon hardware. Traditional von Neumann architectures suffer from a bottleneck between processing and memory, limiting their efficiency for certain classes of problems. Neuromorphic chips, such as Intel's Loihi and IBM's TrueNorth, organize computing elements in neural-inspired configurations that process information through spike-based communication. This approach promises dramatic improvements in energy efficiency and real-time processing for applications in robotics, edge computing, sensory processing, and autonomous systems." },
            { id: 'g_p_120_9', text: "The geopolitical implications of resource scarcity are becoming more acute as the global population continues to grow and standards of living rise in developing nations. Competition for freshwater, arable land, and critical minerals such as lithium and cobalt is intensifying. Climate change exacerbates these pressures by altering precipitation patterns and agricultural productivity. International cooperation through multilateral frameworks is essential for managing shared resources sustainably. Technological innovations in desalination, precision agriculture, and recycling offer promising pathways, but they require significant investment and equitable access to prevent further widening of global inequality." },
            { id: 'g_p_120_10', text: "The philosophy of consciousness remains one of the deepest and most intractable problems in both science and philosophy. Despite extraordinary advances in neuroscience, we still lack a satisfactory explanation for how subjective experience arises from physical processes in the brain. The hard problem of consciousness, as articulated by philosopher David Chalmers, asks why and how physical processes give rise to qualia, the subjective qualities of experience. Competing theories, including integrated information theory, global workspace theory, and panpsychism, each offer partial insights but none has achieved consensus. Resolving this question may require entirely new conceptual frameworks." }
        ]
    }
};
