import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Play, Edit3, Grid, ArrowLeft, Dices, MessageSquare, Swords } from 'lucide-react';
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import axios from 'axios';

const DEBATE_CATEGORIES = {
    "Technology & AI": [
        "AI will displace more jobs than it creates",
        "Privacy is a myth in the digital age",
        "Autonomous vehicles should replace human drivers",
        "Cryptocurrency is the future of finance",
        "Social media algorithms control free will",
        "Humans should merge with machines (Transhumanism)",
        "Deepfakes threaten democracy",
        "Space exploration is a waste of resources",
        "The internet should be a basic human right",
        "Robots should have rights"
    ],
    "Policy & Society": [
        "Universal Basic Income is necessary",
        "Capital punishment should be abolished",
        "Healthcare should be free for all",
        "Social media does more harm than good",
        "Gun control laws need to be stricter",
        "Voting should be mandatory",
        "National borders should be open",
        "The rich should be taxed at 90%",
        "Freedom of speech has limits",
        "Prisons should be for rehabilitation, not punishment"
    ],
    "Education": [
        "Standardized testing is obsolete",
        "College education is overvalued",
        "Student loans should be forgiven",
        "Remote learning is better than classroom learning",
        "Coding should be a mandatory subject",
        "Arts education is as important as STEM",
        "Private schools should be banned",
        "Teachers should be paid more than doctors",
        "Homework does more harm than good",
        "AI tools like ChatGPT should be allowed in exams"
    ],
    "Environment": [
        "Nuclear energy is the best solution for climate change",
        "Plastic ban should be strictly enforced globally",
        "Electric vehicles are not truly eco-friendly yet",
        "Consumption of meat should be banned",
        "Carbon tax is the only way to save the planet",
        "Urbanization is destroying the environment",
        "Overpopulation is the root cause of climate crisis",
        "Individual action vs Corporate responsibility",
        "Space mining is necessary for Earth's survival",
        "Zoos should be abolished"
    ],
    "Economy & Finance": [
        "Capitalism is failing the working class",
        "Gig economy exploits workers",
        "Globalization has increased inequality",
        "Cashless society is dangerous",
        "Minimum wage should be a living wage",
        "Housing should be guaranteed by the state",
        "Rich countries should pay for poor countries' debt",
        "Billionaires should not exist",
        "Freelancing is better than a 9-5 job",
        "Unions are essential for modern economy"
    ],
    "Health & Bioethics": [
        "Euthanasia should be legal",
        "Genetic engineering of babies is ethical",
        "Vaccination should be mandatory for all",
        "Mental health days should be mandatory",
        "Sugar should be regulated like tobacco",
        "Animal testing for medicine is justified",
        "Organ donation should be mandatory after death",
        "Healthcare is a right, not a privilege",
        "Fast food chains are responsible for obesity",
        "Performance enhancing drugs in sports should be allowed"
    ],
    "International Relations": [
        "The UN is ineffective and outdated",
        "Globalization is dead",
        "Nationalism is rising globally",
        "Cyber warfare is the new cold war",
        "Countries should not interfere in others' internal affairs",
        "Refugee crises are a global responsibility",
        "Economic sanctions do not work",
        "A single world government is the future",
        "Space should be a neutral zone",
        "Foreign aid does more harm than good"
    ],
    "Media & Culture": [
        "Cancel culture is toxic",
        "Traditional media is dying",
        "Influencers are the new celebrities",
        "Video games cause violence",
        "Art generated by AI is not real art",
        "Cultural appropriation is a serious issue",
        "Modern music is inferior to classics",
        "Movies are becoming too political",
        "Journalism is no longer objective",
        "Reality TV sends the wrong message"
    ],
    "Workplace & Corporate": [
        "4-day work week should be standard",
        "Remote work is here to stay",
        "Corporate culture is often toxic",
        "CEOs are paid too much",
        "Diversity quotas are necessary",
        "Unpaid internships should be illegal",
        "Employees should own shares of their company",
        "Side hustles are a necessity",
        "Office dress codes are outdated",
        "AI will replace middle management"
    ],
    "Ethics & Philosophy": [
        "Money cannot buy happiness",
        "The end justifies the means",
        "Truth is relative",
        "Human nature is inherently evil",
        "Success is luck, not hard work",
        "We are living in a simulation",
        "Free will is an illusion",
        "Altruism does not exist",
        "Privacy is more important than security",
        "Immortality would be a curse"
    ]
};

const DebateTopicSelection = () => {
    const navigate = useNavigate();
    const [selectedTopic, setSelectedTopic] = useState('');
    const [manualTopic, setManualTopic] = useState('');
    const [selectedCategory, setSelectedCategory] = useState<string>('Policy & Society');
    const [activeTab, setActiveTab] = useState('manual');
    const [userStance, setUserStance] = useState<'Pro' | 'Con'>('Pro');
    const [loadingRandom, setLoadingRandom] = useState(false);

    const handleRandomTopic = async () => {
        setLoadingRandom(true);
        try {
            const response = await axios.post('http://localhost:5003/api/groq/debate/topic');
            if (response.data.success) {
                setSelectedTopic(response.data.topic);
                toast.success("Random topic generated!");
            }
        } catch (error) {
            console.error(error);
            toast.error("Failed to generate topic. Using fallback.");
            // Fallback (just in case API fails)
            const all = Object.values(DEBATE_CATEGORIES).flat();
            setSelectedTopic(all[Math.floor(Math.random() * all.length)]);
        } finally {
            setLoadingRandom(false);
        }
    };

    const handleStart = () => {
        const topicToUse = manualTopic || selectedTopic;
        if (!topicToUse.trim()) {
            toast.error("Please select or enter a topic to proceed.");
            return;
        }
        navigate('/dashboard/debate/room', { state: { topic: topicToUse, stance: userStance } });
    };

    return (
        <div className="w-full h-full min-h-[calc(100vh-4rem)] bg-background text-foreground p-4 md:p-8 flex flex-col items-center justify-center font-sans relative overflow-hidden">

            {/* Background Decorations */}
            <div className="absolute inset-0 -z-10 overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] left-[-5%] w-[500px] h-[500px] bg-red-500/10 rounded-full blur-[100px] animate-pulse" />
                <div className="absolute bottom-[-10%] right-[-5%] w-[400px] h-[400px] bg-orange-500/10 rounded-full blur-[80px] animate-pulse" style={{ animationDelay: '1s' }} />
            </div>

            <div className="w-full max-w-5xl space-y-8 relative z-10">
                {/* Header */}
                <div className="flex flex-col md:flex-row items-center justify-between gap-4 animate-fade-in-down">
                    <Button
                        variant="ghost"
                        onClick={() => navigate('/dashboard/debate')}
                        className="text-muted-foreground hover:text-foreground group"
                    >
                        <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" /> Back
                    </Button>
                    <div className="text-center md:text-left">
                        <div className="flex items-center justify-center md:justify-start gap-2 mb-1">
                            <Badge variant="outline" className="border-red-500/50 text-red-500 bg-red-500/5">
                                <Swords className="w-3 h-3 mr-1" /> Phase 1
                            </Badge>
                        </div>
                        <h1 className="text-3xl md:text-4xl font-bold tracking-tight font-display">
                            Topic & <span className="text-red-500">Stance</span>
                        </h1>
                        <p className="text-muted-foreground mt-1 max-w-lg">
                            Choose what to debate and which side you want to take.
                        </p>
                    </div>
                    <div className="hidden md:block w-[100px]" />
                </div>

                <div className="grid md:grid-cols-12 gap-8 items-start">

                    {/* Left Panel: Selection Method */}
                    <div className="md:col-span-7 glass-card p-6 md:p-8 space-y-6 animate-fade-in-up shadow-xl duration-500">

                        <Tabs defaultValue="manual" value={activeTab} onValueChange={setActiveTab} className="w-full">
                            <TabsList className="grid w-full grid-cols-3 mb-6 p-1 bg-muted/50 rounded-xl">
                                <TabsTrigger value="manual" onClick={() => setSelectedTopic('')}>Manual</TabsTrigger>
                                <TabsTrigger value="random" onClick={() => setSelectedTopic('')}>Random</TabsTrigger>
                                <TabsTrigger value="categories" onClick={() => setSelectedTopic('')}>Category</TabsTrigger>
                            </TabsList>

                            {/* Manual Entry */}
                            <TabsContent value="manual" className="space-y-4 pt-2 animate-slide-up">
                                <div className="space-y-3">
                                    <label className="text-sm font-medium flex items-center gap-2">
                                        <Edit3 className="w-4 h-4 text-primary" /> Enter your topic
                                    </label>
                                    <Input
                                        placeholder="e.g. AI is dangerous for humanity"
                                        className="bg-background/50 border-input h-12 text-lg focus-visible:ring-red-500"
                                        value={manualTopic}
                                        onChange={(e) => {
                                            setManualTopic(e.target.value);
                                            setSelectedTopic('');
                                        }}
                                    />
                                </div>
                            </TabsContent>

                            {/* Random Selection */}
                            <TabsContent value="random" className="space-y-6 pt-2 text-center animate-slide-up">
                                <div className="bg-gradient-to-br from-background/80 to-muted/50 p-8 rounded-2xl border border-dashed border-border flex flex-col items-center justify-center min-h-[140px]">
                                    {selectedTopic ? (
                                        <p className="text-xl font-semibold text-primary animate-in fade-in zoom-in duration-300 leading-tight">
                                            "{selectedTopic}"
                                        </p>
                                    ) : (
                                        <div className="flex flex-col items-center gap-2 text-muted-foreground/70">
                                            <MessageSquare className="w-8 h-8 opacity-50" />
                                            <p className="italic">Roll to get a debate motion</p>
                                        </div>
                                    )}
                                </div>
                                <Button
                                    variant="outline"
                                    size="lg"
                                    onClick={handleRandomTopic}
                                    disabled={loadingRandom}
                                    className="w-full gap-2 border-primary/20 hover:bg-primary/5 hover:text-primary transition-all duration-300 h-12"
                                >
                                    <Dices className={cn("w-5 h-5", loadingRandom && "animate-spin")} />
                                    {loadingRandom ? "Generating..." : "Generate Topic"}
                                </Button>
                            </TabsContent>

                            {/* Category Selection */}
                            <TabsContent value="categories" className="space-y-4 pt-2 animate-slide-up">
                                <div className="space-y-4">
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium flex items-center gap-2">
                                            <Grid className="w-4 h-4 text-primary" /> Select Category
                                        </label>
                                        <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                                            <SelectTrigger className="bg-background/50 h-11"><SelectValue /></SelectTrigger>
                                            <SelectContent>
                                                {Object.keys(DEBATE_CATEGORIES).map(cat => (
                                                    <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium">Choose Topic</label>
                                        <Select
                                            value={selectedTopic}
                                            onValueChange={(val) => {
                                                setSelectedTopic(val);
                                                setManualTopic('');
                                            }}
                                        >
                                            <SelectTrigger className="bg-background/50 h-11">
                                                <SelectValue placeholder="Select a specific topic..." />
                                            </SelectTrigger>
                                            <SelectContent>
                                                {DEBATE_CATEGORIES[selectedCategory as keyof typeof DEBATE_CATEGORIES].map(topic => (
                                                    <SelectItem key={topic} value={topic}>{topic}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </div>
                            </TabsContent>
                        </Tabs>

                        {/* Stance Selection */}
                        <div className="space-y-3 pt-4 border-t">
                            <label className="text-sm font-medium flex items-center gap-2">
                                <Swords className="w-4 h-4 text-primary" /> Your Stance (Side)
                            </label>
                            <div className="grid grid-cols-2 gap-4">
                                <div
                                    className={cn(
                                        "cursor-pointer border rounded-xl p-4 text-center transition-all duration-200 hover:scale-[1.02]",
                                        userStance === 'Pro' ? "bg-green-500/10 border-green-500 shadow-md ring-1 ring-green-500/50" : "bg-card hover:bg-accent/50 border-transparent hover:border-border"
                                    )}
                                    onClick={() => setUserStance('Pro')}
                                >
                                    <h3 className={cn("font-bold text-lg", userStance === 'Pro' ? "text-green-600" : "text-muted-foreground")}>For (Pro)</h3>
                                    <p className="text-xs text-muted-foreground">You support the motion</p>
                                </div>
                                <div
                                    className={cn(
                                        "cursor-pointer border rounded-xl p-4 text-center transition-all duration-200 hover:scale-[1.02]",
                                        userStance === 'Con' ? "bg-red-500/10 border-red-500 shadow-md ring-1 ring-red-500/50" : "bg-card hover:bg-accent/50 border-transparent hover:border-border"
                                    )}
                                    onClick={() => setUserStance('Con')}
                                >
                                    <h3 className={cn("font-bold text-lg", userStance === 'Con' ? "text-red-600" : "text-muted-foreground")}>Against (Con)</h3>
                                    <p className="text-xs text-muted-foreground">You oppose the motion</p>
                                </div>
                            </div>
                        </div>

                    </div>

                    {/* Right Panel: Preview */}
                    <div className="md:col-span-5 space-y-6">
                        <div className="group relative">
                            <div className="absolute -inset-0.5 bg-gradient-to-r from-red-500 to-orange-500 opacity-30 blur rounded-2xl group-hover:opacity-50 transition duration-500" />
                            <div className="relative glass-card p-6 md:p-8 flex flex-col items-center text-center space-y-6 h-full justify-between bg-card">
                                <div className="space-y-2">
                                    <h3 className="text-sm font-medium uppercase tracking-wider text-muted-foreground">Debate Summary</h3>
                                    <div className="min-h-[3rem] flex items-center justify-center flex-col gap-2">
                                        {manualTopic || selectedTopic ? (
                                            <>
                                                <p className="text-xl font-bold leading-tight text-foreground">
                                                    "{manualTopic || selectedTopic}"
                                                </p>
                                                <Badge variant={userStance === 'Pro' ? 'default' : 'destructive'} className="mt-2 text-md px-3 py-1">
                                                    You are: {userStance}
                                                </Badge>
                                            </>
                                        ) : (
                                            <p className="text-lg text-muted-foreground/50 italic">
                                                (Waiting for setup...)
                                            </p>
                                        )}
                                    </div>
                                </div>

                                <div className="w-full pt-4">
                                    <Button
                                        size="lg"
                                        className={cn(
                                            "w-full h-14 text-lg shadow-lg transition-all duration-300 rounded-xl",
                                            !manualTopic && !selectedTopic ? "opacity-50 cursor-not-allowed" : "hover:scale-[1.02] hover:-translate-y-1 bg-gradient-to-r from-red-600 to-orange-600 text-white"
                                        )}
                                        onClick={handleStart}
                                        disabled={!manualTopic && !selectedTopic}
                                    >
                                        <Play className="w-5 h-5 mr-3 fill-white" />
                                        Enter Debate Room
                                    </Button>
                                    <p className="text-[10px] text-muted-foreground/60 mt-3">
                                        You will face an intelligent AI opponent.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
};

export default DebateTopicSelection;
