import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Play, Edit3, Grid, ArrowLeft, Dices, MessageSquare, Swords, Globe, Scale, Timer, BarChart3 } from 'lucide-react';
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { api } from '@/lib/api';

const DEBATE_CATEGORIES = {
    "Technology & AI": [
        "AI will displace more jobs than it creates",
        "Privacy is a myth in the digital age",
        "Autonomous vehicles should replace human drivers",
        "Cryptocurrency is the future of finance",
        "Social media algorithms control free will",
        "Humans should merge with machines (Transhumanism)",
        "Deepfakes threaten democracy",
        "Space exploration is a waste of resources",
        "The internet should be a basic human right",
        "Robots should have rights"
    ],
    "Policy & Society": [
        "Universal Basic Income is necessary",
        "Capital punishment should be abolished",
        "Healthcare should be free for all",
        "Social media does more harm than good",
        "Gun control laws need to be stricter",
        "Voting should be mandatory",
        "National borders should be open",
        "The rich should be taxed at 90%",
        "Freedom of speech has limits",
        "Prisons should be for rehabilitation, not punishment"
    ],
    "Education": [
        "Standardized testing is obsolete",
        "College education is overvalued",
        "Student loans should be forgiven",
        "Remote learning is better than classroom learning",
        "Coding should be a mandatory subject",
        "Arts education is as important as STEM",
        "Private schools should be banned",
        "Teachers should be paid more than doctors",
        "Homework does more harm than good",
        "AI tools like ChatGPT should be allowed in exams"
    ],
    "Environment": [
        "Nuclear energy is the best solution for climate change",
        "Plastic ban should be strictly enforced globally",
        "Electric vehicles are not truly eco-friendly yet",
        "Consumption of meat should be banned",
        "Carbon tax is the only way to save the planet",
        "Urbanization is destroying the environment",
        "Overpopulation is the root cause of climate crisis",
        "Individual action vs Corporate responsibility",
        "Space mining is necessary for Earth's survival",
        "Zoos should be abolished"
    ],
    "Economy & Finance": [
        "Capitalism is failing the working class",
        "Gig economy exploits workers",
        "Globalization has increased inequality",
        "Cashless society is dangerous",
        "Minimum wage should be a living wage",
        "Housing should be guaranteed by the state",
        "Rich countries should pay for poor countries' debt",
        "Billionaires should not exist",
        "Freelancing is better than a 9-5 job",
        "Unions are essential for modern economy"
    ],
    "Health & Bioethics": [
        "Euthanasia should be legal",
        "Genetic engineering of babies is ethical",
        "Vaccination should be mandatory for all",
        "Mental health days should be mandatory",
        "Sugar should be regulated like tobacco",
        "Animal testing for medicine is justified",
        "Organ donation should be mandatory after death",
        "Healthcare is a right, not a privilege",
        "Fast food chains are responsible for obesity",
        "Performance enhancing drugs in sports should be allowed"
    ],
    "International Relations": [
        "The UN is ineffective and outdated",
        "Globalization is dead",
        "Nationalism is rising globally",
        "Cyber warfare is the new cold war",
        "Countries should not interfere in others' internal affairs",
        "Refugee crises are a global responsibility",
        "Economic sanctions do not work",
        "A single world government is the future",
        "Space should be a neutral zone",
        "Foreign aid does more harm than good"
    ],
    "Media & Culture": [
        "Cancel culture is toxic",
        "Traditional media is dying",
        "Influencers are the new celebrities",
        "Video games cause violence",
        "Art generated by AI is not real art",
        "Cultural appropriation is a serious issue",
        "Modern music is inferior to classics",
        "Movies are becoming too political",
        "Journalism is no longer objective",
        "Reality TV sends the wrong message"
    ],
    "Workplace & Corporate": [
        "4-day work week should be standard",
        "Remote work is here to stay",
        "Corporate culture is often toxic",
        "CEOs are paid too much",
        "Diversity quotas are necessary",
        "Unpaid internships should be illegal",
        "Employees should own shares of their company",
        "Side hustles are a necessity",
        "Office dress codes are outdated",
        "AI will replace middle management"
    ],
    "Ethics & Philosophy": [
        "Money cannot buy happiness",
        "The end justifies the means",
        "Truth is relative",
        "Human nature is inherently evil",
        "Success is luck, not hard work",
        "We are living in a simulation",
        "Free will is an illusion",
        "Altruism does not exist",
        "Privacy is more important than security",
        "Immortality would be a curse"
    ]
};

const DebateTopicSelection = () => {
    const navigate = useNavigate();
    const [selectedTopic, setSelectedTopic] = useState('');
    const [manualTopic, setManualTopic] = useState('');
    const [selectedCategory, setSelectedCategory] = useState<string>('Technology & AI');
    const [activeTab, setActiveTab] = useState('manual');
    const [userStance, setUserStance] = useState<'Pro' | 'Con'>('Pro');
    const [timeLimit, setTimeLimit] = useState<number>(5); // Time limit in minutes (5-10)
    const [loadingRandom, setLoadingRandom] = useState(false);

    const handleRandomTopic = async () => {
        setLoadingRandom(true);
        try {
            const response = await api.post('/groq/debate/topic', {
                type: 'debate',
                category: 'General'
            });
            if (response.data.success) {
                setSelectedTopic(response.data.topic);
                toast.success("Random topic generated!", {
                    className: "bg-blue-500 text-white border-blue-600"
                });
            }
        } catch (error) {
            console.error(error);
            toast.error("Failed to generate topic. Using fallback.");
            const all = Object.values(DEBATE_CATEGORIES).flat();
            setSelectedTopic(all[Math.floor(Math.random() * all.length)]);
        } finally {
            setLoadingRandom(false);
        }
    };

    const handleStart = () => {
        const topicToUse = manualTopic || selectedTopic;
        if (!topicToUse.trim()) {
            toast.error("Please select or enter a topic to proceed.");
            return;
        }
        navigate('/dashboard/debate/room', { state: { topic: topicToUse, stance: userStance, timeLimit } });
    };

    return (
        <div className="w-full h-full min-h-[calc(100vh-4rem)] bg-background text-foreground flex flex-col items-center justify-center font-sans relative overflow-hidden py-4 px-6 md:px-12">

            {/* Background Decorations - Blue Theme */}
            <div className="absolute inset-0 -z-10 overflow-hidden pointer-events-none">
                <div className="absolute top-[-10%] left-[-5%] w-[500px] h-[500px] bg-blue-500/10 rounded-full blur-[100px] animate-pulse" />
                <div className="absolute bottom-[-10%] right-[-5%] w-[400px] h-[400px] bg-indigo-500/10 rounded-full blur-[80px] animate-pulse" style={{ animationDelay: '1s' }} />
                <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-full h-full bg-[url('/grid.svg')] opacity-[0.03] bg-repeat" />
            </div>

            {/* Main Content Container - Secured & Squared - INCREASED WIDTH NO SCROLL */}
            <div className="w-full max-w-6xl relative z-10 flex flex-col h-full justify-center">

                {/* Header */}
                <div className="flex flex-col items-center text-center space-y-3 mb-6 animate-fade-in-down shrink-0">
                    <Badge variant="outline" className="border-blue-500/50 text-blue-600 bg-blue-500/5 px-4 py-1.5 text-sm uppercase tracking-wider backdrop-blur-sm">
                        <Swords className="w-3.5 h-3.5 mr-2" /> Phase 1: Setup
                    </Badge>
                    <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground">
                        Topic & <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">Stance</span>
                    </h1>
                    <p className="text-lg text-muted-foreground max-w-lg">
                        Define the battlefield. Choose your debate motion and pick your side.
                    </p>
                </div>

                <div className="bg-card/60 backdrop-blur-xl border border-border/50 rounded-3xl shadow-2xl overflow-hidden grid md:grid-cols-12 min-h-[450px] animate-fade-in-up flex-grow max-h-[600px]">

                    {/* Left Panel: Inputs (7 Columns) */}
                    <div className="md:col-span-7 p-6 space-y-4 border-b md:border-b-0 md:border-r border-border/50 flex flex-col h-full max-h-[600px] overflow-y-auto custom-scrollbar">

                        <Tabs defaultValue="manual" value={activeTab} onValueChange={setActiveTab} className="w-full flex-shrink-0">
                            <TabsList className="grid w-full grid-cols-3 mb-4 p-1.5 bg-muted/50 rounded-xl h-auto shrink-0">
                                <TabsTrigger value="manual" onClick={() => setSelectedTopic('')} className="py-2.5 data-[state=active]:bg-background data-[state=active]:text-blue-600 data-[state=active]:shadow-sm transition-all text-muted-foreground font-medium">Manual</TabsTrigger>
                                <TabsTrigger value="random" onClick={() => setSelectedTopic('')} className="py-2.5 data-[state=active]:bg-background data-[state=active]:text-blue-600 data-[state=active]:shadow-sm transition-all text-muted-foreground font-medium">Random</TabsTrigger>
                                <TabsTrigger value="categories" onClick={() => setSelectedTopic('')} className="py-2.5 data-[state=active]:bg-background data-[state=active]:text-blue-600 data-[state=active]:shadow-sm transition-all text-muted-foreground font-medium">Category</TabsTrigger>
                            </TabsList>

                            {/* Manual Entry */}
                            <TabsContent value="manual" className="space-y-3 pt-2 animate-in fade-in slide-in-from-left-4 duration-300 mt-0">
                                <div className="space-y-3">
                                    <label className="text-sm font-medium flex items-center gap-2 text-foreground/80">
                                        <Edit3 className="w-4 h-4 text-blue-500" /> Enter specific motion
                                    </label>
                                    <Input
                                        placeholder="e.g. AI is dangerous for humanity"
                                        className="bg-background/50 border-input h-12 text-base focus-visible:ring-blue-500 focus-visible:ring-offset-0 px-4 rounded-xl shadow-sm transition-all hover:bg-background/80"
                                        value={manualTopic}
                                        onChange={(e) => {
                                            setManualTopic(e.target.value);
                                            setSelectedTopic('');
                                        }}
                                    />
                                </div>
                            </TabsContent>

                            {/* Random Selection */}
                            <TabsContent value="random" className="space-y-4 pt-2 text-center animate-in fade-in slide-in-from-left-4 duration-300 mt-0">
                                <div className="bg-gradient-to-br from-blue-50/50 to-indigo-50/50 dark:from-blue-900/10 dark:to-indigo-900/10 p-4 rounded-2xl border border-dashed border-blue-200 dark:border-blue-800 flex flex-col items-center justify-center min-h-[100px] relative group transition-colors hover:bg-blue-100/30">
                                    {selectedTopic ? (
                                        <p className="text-lg font-semibold text-blue-700 dark:text-blue-300 animate-in fade-in zoom-in duration-300 leading-snug px-4">
                                            "{selectedTopic}"
                                        </p>
                                    ) : (
                                        <div className="flex flex-col items-center gap-3 text-muted-foreground/60">
                                            <div className="w-12 h-12 rounded-full bg-background flex items-center justify-center shadow-sm">
                                                <Dices className="w-6 h-6 text-blue-400" />
                                            </div>
                                            <p className="text-sm font-medium">Click to generate a motion</p>
                                        </div>
                                    )}
                                </div>
                                <Button
                                    variant="outline"
                                    size="lg"
                                    onClick={handleRandomTopic}
                                    disabled={loadingRandom}
                                    className="w-full gap-2 border-blue-200 hover:border-blue-300 hover:bg-blue-50 text-blue-700 h-12 rounded-xl"
                                >
                                    <Globe className={cn("w-5 h-5", loadingRandom && "animate-spin")} />
                                    {loadingRandom ? "Consulting AI..." : "Generate AI Motion"}
                                </Button>
                            </TabsContent>

                            {/* Category Selection */}
                            <TabsContent value="categories" className="space-y-3 pt-2 animate-in fade-in slide-in-from-left-4 duration-300 mt-0">
                                <div className="space-y-5">
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/80">
                                            <Grid className="w-4 h-4 text-blue-500" /> Topic Domain
                                        </label>
                                        <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                                            <SelectTrigger className="bg-background/50 h-12 rounded-xl border-input focus:ring-blue-500">
                                                <SelectValue />
                                            </SelectTrigger>
                                            <SelectContent>
                                                {Object.keys(DEBATE_CATEGORIES).map(cat => (
                                                    <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/80">
                                            <MessageSquare className="w-4 h-4 text-blue-500" /> Specific Motion
                                        </label>
                                        <Select
                                            value={selectedTopic}
                                            onValueChange={(val) => {
                                                setSelectedTopic(val);
                                                setManualTopic('');
                                            }}
                                        >
                                            <SelectTrigger className="bg-background/50 h-12 rounded-xl border-input focus:ring-blue-500">
                                                <SelectValue placeholder="Choose a motion..." />
                                            </SelectTrigger>
                                            <SelectContent className="max-h-[300px]">
                                                {DEBATE_CATEGORIES[selectedCategory as keyof typeof DEBATE_CATEGORIES].map(topic => (
                                                    <SelectItem key={topic} value={topic}>{topic}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </div>
                            </TabsContent>
                        </Tabs>

                        {/* Stance Selection - Semantic Colors Retained */}
                        <div className="pt-3 flex-shrink-0">
                            <label className="text-sm font-medium flex items-center gap-2 mb-3 text-foreground/80">
                                <Scale className="w-4 h-4 text-blue-500" /> Choose Your Side
                            </label>
                            <div className="grid grid-cols-2 gap-4">
                                <div
                                    className={cn(
                                        "cursor-pointer border rounded-2xl p-3 text-center transition-all duration-300 hover:scale-[1.02] flex flex-col items-center justify-center gap-1.5 h-18",
                                        userStance === 'Pro'
                                            ? "bg-emerald-500/10 border-emerald-500 dark:border-emerald-400 shadow-md shadow-emerald-500/10 ring-1 ring-emerald-500/50"
                                            : "bg-background/50 border-border hover:border-emerald-200 hover:bg-emerald-50/30"
                                    )}
                                    onClick={() => setUserStance('Pro')}
                                >
                                    <div className={cn("w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold", userStance === 'Pro' ? "bg-emerald-100 text-emerald-600" : "bg-muted text-muted-foreground")}>P</div>
                                    <div>
                                        <h3 className={cn("font-semibold text-xs", userStance === 'Pro' ? "text-emerald-700 dark:text-emerald-400" : "text-muted-foreground")}>Proponent</h3>
                                        <p className="text-[9px] text-muted-foreground">Agree</p>
                                    </div>
                                </div>
                                <div
                                    className={cn(
                                        "cursor-pointer border rounded-2xl p-3 text-center transition-all duration-300 hover:scale-[1.02] flex flex-col items-center justify-center gap-1.5 h-18",
                                        userStance === 'Con'
                                            ? "bg-rose-500/10 border-rose-500 dark:border-rose-400 shadow-md shadow-rose-500/10 ring-1 ring-rose-500/50"
                                            : "bg-background/50 border-border hover:border-rose-200 hover:bg-rose-50/30"
                                    )}
                                    onClick={() => setUserStance('Con')}
                                >
                                    <div className={cn("w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold", userStance === 'Con' ? "bg-rose-100 text-rose-600" : "bg-muted text-muted-foreground")}>O</div>
                                    <div>
                                        <h3 className={cn("font-semibold text-xs", userStance === 'Con' ? "text-rose-700 dark:text-rose-400" : "text-muted-foreground")}>Opponent</h3>
                                        <p className="text-[9px] text-muted-foreground">Disagree</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Time Limit Selection */}
                        <div className="pt-3 flex-shrink-0">
                            <label className="text-sm font-medium flex items-center gap-2 mb-3 text-foreground/80">
                                <Timer className="w-4 h-4 text-blue-500" /> Debate Duration
                            </label>
                            <div className="grid grid-cols-6 gap-2">
                                {[5, 6, 7, 8, 9, 10].map((minutes) => (
                                    <div
                                        key={minutes}
                                        className={cn(
                                            "cursor-pointer border rounded-xl p-2 text-center transition-all duration-300 hover:scale-[1.05] flex flex-col items-center justify-center gap-0.5",
                                            timeLimit === minutes
                                                ? "bg-blue-500/10 border-blue-500 dark:border-blue-400 shadow-md shadow-blue-500/10 ring-1 ring-blue-500/50"
                                                : "bg-background/50 border-border hover:border-blue-200 hover:bg-blue-50/30"
                                        )}
                                        onClick={() => setTimeLimit(minutes)}
                                    >
                                        <div className={cn("text-base font-bold", timeLimit === minutes ? "text-blue-700 dark:text-blue-400" : "text-muted-foreground")}>{minutes}</div>
                                        <div className="text-[9px] text-muted-foreground uppercase">min</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Right Panel: Preview & Start (5 Columns) */}
                    <div className="md:col-span-5 bg-muted/30 p-8 flex flex-col justify-center items-center text-center space-y-8 relative h-full">
                        {/* Decorative Blur */}
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl pointer-events-none" />

                        <div className="relative z-10 w-full max-w-sm space-y-8 flex flex-col h-full justify-center">

                            {/* Matchup Preview */}
                            <div className="space-y-6 flex-grow flex flex-col justify-center">
                                <h3 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground/70">Session Preview</h3>

                                {manualTopic || selectedTopic ? (
                                    <div className="animate-in fade-in zoom-in duration-300 space-y-6">
                                        <h4 className="text-2xl font-bold leading-tight text-foreground line-clamp-4 px-2">
                                            "{manualTopic || selectedTopic}"
                                        </h4>

                                        {/* Dynamic Matchup Display */}
                                        <div className="flex items-center justify-center gap-4 pt-2">
                                            {/* User Box */}
                                            <div className="flex flex-col items-center gap-2">
                                                <Badge variant="secondary" className={cn("px-3 py-1 text-xs border font-bold h-8", userStance === 'Pro' ? "bg-emerald-100/50 text-emerald-700 border-emerald-200" : "bg-rose-100/50 text-rose-700 border-rose-200")}>
                                                    YOU: {userStance === 'Pro' ? 'Proponent' : 'Opponent'}
                                                </Badge>
                                            </div>

                                            <span className="text-muted-foreground text-xs font-bold">VS</span>

                                            {/* AI Box (Opposite Logic) */}
                                            <div className="flex flex-col items-center gap-2">
                                                <Badge variant="outline" className={cn("px-3 py-1 text-xs border border-dashed font-bold h-8 opacity-70", userStance === 'Pro' ? "border-rose-400 text-rose-600 bg-rose-50" : "border-emerald-400 text-emerald-600 bg-emerald-50")}>
                                                    AI: {userStance === 'Pro' ? 'Opponent' : 'Proponent'}
                                                </Badge>
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="text-muted-foreground/40 py-12 border-2 border-dashed border-border/50 rounded-2xl bg-background/50 flex flex-col items-center justify-center h-48">
                                        <MessageSquare className="w-10 h-10 mx-auto mb-3 opacity-50" />
                                        <p className="text-sm font-medium">Select a topic to preview matchup</p>
                                    </div>
                                )}
                            </div>

                            <Button
                                size="lg"
                                className={cn(
                                    "w-full h-14 text-lg font-semibold rounded-xl shadow-xl shadow-blue-500/10 transition-all duration-300 mt-auto",
                                    !manualTopic && !selectedTopic
                                        ? "opacity-50 cursor-not-allowed bg-muted text-muted-foreground"
                                        : "hover:scale-[1.02] hover:-translate-y-1 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white"
                                )}
                                onClick={handleStart}
                                disabled={!manualTopic && !selectedTopic}
                            >
                                <Play className="w-5 h-5 mr-2 fill-white" />
                                Enter Debate Room
                            </Button>
                        </div>
                    </div>

                </div>
            </div>

            {/* Top Buttons (Absolute) */}
            <div className="absolute top-6 left-6 z-20">
                <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => navigate('/dashboard/debate')}
                    className="text-muted-foreground hover:text-foreground hover:bg-background/80"
                >
                    <ArrowLeft className="w-4 h-4 mr-2" /> Back
                </Button>
            </div>
            
            <div className="absolute top-6 right-6 z-20">
                <Button
                    onClick={() => navigate('/dashboard/debate/performance')}
                    className="h-12 px-6 rounded-2xl bg-gradient-to-r from-emerald-500 to-green-600 hover:from-emerald-600 hover:to-green-700 text-white shadow-lg shadow-emerald-500/20 hover:scale-[1.02] transition-all border-none"
                >
                    <BarChart3 className="w-5 h-5 mr-2" /> 
                    <span className="font-bold text-sm tracking-wide">View Performance</span>
                </Button>
            </div>
        </div>
    );
};

export default DebateTopicSelection;
