import { Question } from "../aptitudeQuestions";

export const numberSeriesQuestions: Question[] = [
    {
        question: "Find the next number in the series: 2, 6, 12, 20, 30, ?",
        options: ["40","42","44","38"],
        correct: 1,
        explanation: "The pattern follows n² + n for consecutive integers (1²+1=2, 2²+2=6, 3²+3=12... 6²+6=42)."
    },
    {
        question: "What comes next in the sequence: 5, 11, 24, 51, 106, ?",
        options: ["217","212","220","215"],
        correct: 0,
        explanation: "Each term is multiplied by 2, and then a sequentially increasing number is added (x2+1, x2+2, x2+3, x2+4, x2+5), so 106 x 2 + 5 = 217."
    },
    {
        question: "Find the missing term: 1, 4, 27, 16, 125, 36, ?",
        options: ["49","216","343","64"],
        correct: 2,
        explanation: "The series alternates between cubes of odd numbers (1³, 3³, 5³, 7³) and squares of even numbers (2², 4², 6²), so the next is 7³ = 343."
    },
    {
        question: "Complete the series: 3, 8, 15, 24, 35, ?",
        options: ["48","46","44","50"],
        correct: 0,
        explanation: "The numbers follow the pattern of squares minus one (2²-1, 3²-1, 4²-1, 5²-1, 6²-1, 7²-1), making the next term 48."
    },
    {
        question: "Identify the next number: 10, 18, 28, 40, 54, ?",
        options: ["68","72","70","74"],
        correct: 2,
        explanation: "The differences between consecutive terms are increasing even numbers (+8, +10, +12, +14, +16), so 54 + 16 = 70."
    },
    {
        question: "Find the next term: 2, 3, 5, 7, 11, 13, ?",
        options: ["15","17","19","14"],
        correct: 1,
        explanation: "The series is a straightforward list of consecutive prime numbers, making 17 the next term."
    },
    {
        question: "What comes next in the series: 1, 5, 14, 30, 55, ?",
        options: ["81","91","85","90"],
        correct: 1,
        explanation: "The differences between terms are consecutive perfect squares (+4, +9, +16, +25, +36), so 55 + 36 = 91."
    },
    {
        question: "Complete the alternating series: 7, 10, 8, 11, 9, 12, ?",
        options: ["10","13","14","11"],
        correct: 0,
        explanation: "The sequence has two alternating sub-series: 7, 8, 9, 10 and 10, 11, 12; hence the next number is 10."
    },
    {
        question: "Find the missing term: 120, 99, 80, 63, 48, ?",
        options: ["35","36","39","32"],
        correct: 0,
        explanation: "The series consists of squares minus one in descending order (11²-1, 10²-1, 9²-1, 8²-1, 7²-1, 6²-1 = 35)."
    },
    {
        question: "What is the next number in the series: 3, 6, 18, 72, ?",
        options: ["360","288","144","432"],
        correct: 0,
        explanation: "Each term is multiplied by an increasing integer (x2, x3, x4, x5), so 72 x 5 = 360."
    },
    {
        question: "Find the missing term: 2, 5, 10, 17, 26, ?",
        options: ["35","37","39","41"],
        correct: 1,
        explanation: "The pattern adds consecutive odd numbers (+3, +5, +7, +9, +11), resulting in 26 + 11 = 37."
    },
    {
        question: "Complete the sequence: 4, 9, 25, 49, 121, ?",
        options: ["144","169","196","225"],
        correct: 1,
        explanation: "The series consists of the squares of consecutive prime numbers (2², 3², 5², 7², 11², 13² = 169)."
    },
    {
        question: "Identify the next term: 8, 28, 116, 584, ?",
        options: ["3508","1752","2336","2920"],
        correct: 0,
        explanation: "The pattern is multiply by an increasing integer and add 4 (x3+4, x4+4, x5+4, x6+4), so 584 x 6 + 4 = 3508."
    },
    {
        question: "Find the next number: 13, 35, 57, 79, 911, ?",
        options: ["1112","1113","1315","1011"],
        correct: 1,
        explanation: "Each term is formed by concatenating two consecutive odd numbers (1-3, 3-5, 5-7, 7-9, 9-11, 11-13)."
    },
    {
        question: "Complete the series: 71, 55, 46, 42, ?",
        options: ["39","40","41","38"],
        correct: 2,
        explanation: "The sequence subtracts decreasing perfect squares (-16, -9, -4, -1), so 42 - 1 = 41."
    },
    {
        question: "Find the next term: 2, 12, 36, 80, 150, ?",
        options: ["252","194","210","240"],
        correct: 0,
        explanation: "The series follows the formula n³ + n² (1³+1², 2³+2², 3³+3²... 6³+6² = 216+36 = 252)."
    },
    {
        question: "Identify the next term in the series: 3, 4, 12, 45, ?",
        options: ["196","144","180","175"],
        correct: 0,
        explanation: "The pattern multiplies by an integer and adds a square (x1+1², x2+2², x3+3², x4+4²), so 45 x 4 + 16 = 196."
    },
    {
        question: "Find the missing term: 2, 3, 8, 27, 112, ?",
        options: ["565","450","336","672"],
        correct: 0,
        explanation: "Each term is generated by multiplying by an increasing integer and adding the next integer (x1+1, x2+2, x3+3, x4+4, x5+5), so 112 x 5 + 5 = 565."
    },
    {
        question: "What comes next in the sequence: 50, 49, 46, 41, 34, ?",
        options: ["27","25","29","23"],
        correct: 1,
        explanation: "The differences between the terms are increasing odd numbers (-1, -3, -5, -7, -9), making 34 - 9 = 25."
    },
    {
        question: "Complete the series: 0, 6, 24, 60, 120, ?",
        options: ["180","216","210","240"],
        correct: 2,
        explanation: "The pattern follows n³ - n for consecutive integers (1³-1, 2³-2, 3³-3, 4³-4, 5³-5, 6³-6 = 210)."
    },
    {
        question: "Find the next number: 11, 13, 17, 19, 23, 29, 31, 37, 41, ?",
        options: ["43","45","47","49"],
        correct: 0,
        explanation: "The series is a simple list of consecutive prime numbers starting from 11, so the next prime is 43."
    },
    {
        question: "What comes next: 1, 2, 6, 21, 88, ?",
        options: ["345","440","445","352"],
        correct: 2,
        explanation: "The pattern is multiply by an increasing integer and add the same integer (x1+1, x2+2, x3+3, x4+4, x5+5), so 88 x 5 + 5 = 445."
    },
    {
        question: "Identify the missing number: 6, 13, 28, 59, ?",
        options: ["120","122","118","124"],
        correct: 1,
        explanation: "Each term is multiplied by 2 and followed by the addition of an increasing integer (x2+1, x2+2, x2+3, x2+4), so 59 x 2 + 4 = 122."
    },
    {
        question: "Find the next term in the series: 3, 10, 29, 66, 127, ?",
        options: ["218","196","216","220"],
        correct: 0,
        explanation: "The numbers are formed by the formula n³ + 2 (1³+2, 2³+2, 3³+2, 4³+2, 5³+2, 6³+2 = 218)."
    },
    {
        question: "Complete the series: 1, 8, 9, 64, 25, 216, ?",
        options: ["49","343","36","125"],
        correct: 0,
        explanation: "The series alternates between squares of odd numbers (1², 3², 5², 7²) and cubes of even numbers (2³, 4³, 6³), making the next term 7² = 49."
    },
    {
        question: "Identify the next term: 9, 27, 31, 155, 161, 1127, ?",
        options: ["1135","1134","2254","1130"],
        correct: 1,
        explanation: "The alternating sequence multiplies by prime numbers and adds the next consecutive integer (x3, +4, x5, +6, x7, +8), so 1127 + 7 = 1134."
    },
    {
        question: "What comes next in the sequence: 4, 18, ?, 100, 180, 294",
        options: ["48","50","42","56"],
        correct: 0,
        explanation: "The pattern follows n³ - n² (2³-2², 3³-3², 4³-4² = 64-16 = 48, 5³-5² = 100)."
    },
    {
        question: "Find the missing term: 10, 14, 26, 42, 70, ?",
        options: ["100","102","112","114"],
        correct: 3,
        explanation: "This is a custom Fibonacci-like series where the current term is the sum of the previous two terms plus 2 (10+14+2=26, 14+26+2=42, 26+42+2=70, 42+70+2=114)."
    },
    {
        question: "Identify the next number: 1, 2, 2, 4, 8, 32, ?",
        options: ["64","128","256","512"],
        correct: 2,
        explanation: "Each term from the third onwards is the product of the two preceding terms (1x2=2, 2x2=4, 2x4=8, 4x8=32, 8x32=256)."
    },
    {
        question: "Complete the sequence: 2, 10, 30, 68, 130, ?",
        options: ["222","216","210","220"],
        correct: 0,
        explanation: "The numbers are generated using the formula n³ + n (1³+1, 2³+2, 3³+3, 4³+4, 5³+5, 6³+6 = 222)."
    },
    {
        question: "Find the missing term: 15, 31, 63, 127, 255, ?",
        options: ["513","511","517","501"],
        correct: 1,
        explanation: "The pattern follows multiplying by 2 and adding 1 (x2+1) each time, so 255 x 2 + 1 = 511."
    },
    {
        question: "What comes next in the series: 3, 7, 23, 95, ?",
        options: ["479","384","475","512"],
        correct: 0,
        explanation: "Each term is formed by multiplying by consecutive integers and adding a consecutive integer (x2+1, x3+2, x4+3, x5+4), so 95 x 5 + 4 = 479."
    },
    {
        question: "Identify the next term: 1000, 200, 40, 8, ?",
        options: ["2","1.6","1.2","1"],
        correct: 1,
        explanation: "Each number is divided by 5 to obtain the next number in the sequence (8 / 5 = 1.6)."
    },
    {
        question: "Find the next term: 8, 4, 4, 6, 12, ?",
        options: ["24","30","18","36"],
        correct: 1,
        explanation: "The series multiplies by incrementally increasing decimals (x0.5, x1, x1.5, x2, x2.5), so 12 x 2.5 = 30."
    },
    {
        question: "Complete the series: 4, 5, 12, 39, 160, ?",
        options: ["805","800","795","810"],
        correct: 0,
        explanation: "The pattern involves multiplying by an integer and adding the same integer (x1+1, x2+2, x3+3, x4+4, x5+5), so 160 x 5 + 5 = 805."
    },
    {
        question: "What comes next in the sequence: 7, 26, 63, 124, 215, ?",
        options: ["343","342","344","511"],
        correct: 1,
        explanation: "The numbers follow the pattern of cubes minus one (2³-1, 3³-1, 4³-1, 5³-1, 6³-1, 7³-1 = 342)."
    },
    {
        question: "Find the missing letters: 2, 10, 26, 50, 82, ?",
        options: ["120","122","118","112"],
        correct: 1,
        explanation: "The pattern follows n² + 1 for odd integers (1²+1, 3²+1, 5²+1, 7²+1, 9²+1, 11²+1 = 122)."
    },
    {
        question: "Identify the next term: 16, 33, 65, 131, 261, ?",
        options: ["523","522","521","525"],
        correct: 0,
        explanation: "The series multiplies by 2 and adds an alternating sequence of +1 and -1 (x2+1, x2-1, x2+1, x2-1, x2+1), so 261 x 2 + 1 = 523."
    },
    {
        question: "Complete the sequence: 5, 16, 51, 158, ?",
        options: ["481","475","485","479"],
        correct: 0,
        explanation: "Each number is multiplied by 3 and then added to a consecutive integer (x3+1, x3+3, x3+5, x3+7), so 158 x 3 + 7 = 481."
    },
    {
        question: "Find the next letter: 1, 1, 2, 6, 24, 120, ?",
        options: ["720","500","840","360"],
        correct: 0,
        explanation: "The series consists of factorials in ascending order (1!, 2!, 3!, 4!, 5!, 6! = 720)."
    },
    {
        question: "What comes next: 1, 8, 27, 64, ?",
        options: ["100","121","125","144"],
        correct: 2,
        explanation: "This is a direct list of perfect cubes (1³, 2³, 3³, 4³, 5³ = 125)."
    },
    {
        question: "Identify the next term in the series: 3, 12, 27, 48, 75, ?",
        options: ["100","108","98","112"],
        correct: 1,
        explanation: "The pattern is 3 x n² (3x1², 3x2², 3x3², 3x4², 3x5², 3x6² = 3 x 36 = 108)."
    },
    {
        question: "Find the missing term: 10, 5, 5, 7.5, 15, ?",
        options: ["37.5","45","30","42.5"],
        correct: 0,
        explanation: "The series multiplies by an increasing decimal value (x0.5, x1, x1.5, x2, x2.5), so 15 x 2.5 = 37.5."
    },
    {
        question: "Complete the series: 2, 9, 28, 65, 126, ?",
        options: ["217","216","215","218"],
        correct: 0,
        explanation: "The sequence follows the rule of cubes plus one (1³+1, 2³+1, 3³+1, 4³+1, 5³+1, 6³+1 = 217)."
    },
    {
        question: "Find the next letter: 1, 4, 10, 22, 46, ?",
        options: ["94","92","90","96"],
        correct: 0,
        explanation: "Each term is formed by multiplying the previous term by 2 and adding 2 (x2+2), resulting in 46 x 2 + 2 = 94."
    },
    {
        question: "What comes next in the sequence: 0, 3, 8, 15, 24, ?",
        options: ["35","34","36","37"],
        correct: 0,
        explanation: "The pattern follows n² - 1 for consecutive integers starting from 1 (1²-1, 2²-1... 6²-1 = 35)."
    },
    {
        question: "Identify the next term: 20, 19, 17, 14, 10, ?",
        options: ["4","5","6","7"],
        correct: 1,
        explanation: "The differences between the numbers decrease consecutively (-1, -2, -3, -4, -5), so 10 - 5 = 5."
    },
    {
        question: "Find the missing letter: 1, 2, 6, 15, 31, ?",
        options: ["56","60","45","50"],
        correct: 0,
        explanation: "The series adds consecutive perfect squares (+1, +4, +9, +16, +25), so 31 + 25 = 56."
    },
    {
        question: "Complete the series: 7, 8, 18, 57, 232, ?",
        options: ["1165","1150","1160","1175"],
        correct: 0,
        explanation: "The pattern is multiplying by an integer and adding the same integer (x1+1, x2+2, x3+3, x4+4, x5+5), so 232 x 5 + 5 = 1165."
    },
    {
        question: "Identify the next letter in the series: 1, 3, 7, 15, 31, ?",
        options: ["63","61","65","67"],
        correct: 0,
        explanation: "Each term is multiplied by 2 and then increased by 1 (x2+1), or alternatively adding powers of 2 (2, 4, 8, 16, 32), so 31 + 32 = 63."
    }
];
