import { ResumeTemplate } from '@/types/resume';

export const resumeTemplates: ResumeTemplate[] = [
    {
        id: 'classic',
        name: 'Classic',
        description: 'Traditional and professional layout, perfect for corporate roles',
        thumbnail: '/templates/classic.png',
        category: 'professional',
        hasPhoto: false,
        atsScore: 98,
    },
    {
        id: 'modern',
        name: 'Modern',
        description: 'Clean lines with a contemporary feel, great for tech positions',
        thumbnail: '/templates/modern.png',
        category: 'modern',
        hasPhoto: false,
        atsScore: 95,
    },
    {
        id: 'minimal',
        name: 'Minimal',
        description: 'Simple and elegant with focus on content',
        thumbnail: '/templates/minimal.png',
        category: 'minimal',
        hasPhoto: false,
        atsScore: 99,
    },
    {
        id: 'executive',
        name: 'Executive',
        description: 'Sophisticated design for senior-level positions',
        thumbnail: '/templates/executive.png',
        category: 'professional',
        hasPhoto: false,
        atsScore: 92,
    },
    {
        id: 'creative',
        name: 'Creative',
        description: 'Stand out with a unique but ATS-friendly design',
        thumbnail: '/templates/creative.png',
        category: 'creative',
        hasPhoto: false,
        atsScore: 88,
    },
    {
        id: 'professional',
        name: 'Professional',
        description: 'Balanced and versatile, suitable for any industry',
        thumbnail: '/templates/professional.png',
        category: 'professional',
        hasPhoto: false,
        atsScore: 96,
    },
    {
        id: 'elegant',
        name: 'Elegant',
        description: 'Refined typography with subtle accents',
        thumbnail: '/templates/elegant.png',
        category: 'modern',
        hasPhoto: true,
        atsScore: 90,
    },
    {
        id: 'bold',
        name: 'Bold',
        description: 'Strong headers and clear hierarchy',
        thumbnail: '/templates/bold.png',
        category: 'modern',
        hasPhoto: false,
        atsScore: 94,
    },
    {
        id: 'compact',
        name: 'Compact',
        description: 'Maximize content in minimal space',
        thumbnail: '/templates/compact.png',
        category: 'minimal',
        hasPhoto: false,
        atsScore: 97,
    },
    {
        id: 'tech',
        name: 'Tech',
        description: 'Designed for developers and IT professionals',
        thumbnail: '/templates/tech.png',
        category: 'modern',
        hasPhoto: false,
        atsScore: 95,
    },
    {
        id: 'sidebar',
        name: 'Sidebar',
        description: 'Two-column layout with sidebar for skills and contact',
        thumbnail: '/templates/sidebar.png',
        category: 'modern',
        hasPhoto: true,
        atsScore: 91,
    },
    {
        id: 'corporate',
        name: 'Corporate',
        description: 'Traditional corporate style with clean structure',
        thumbnail: '/templates/corporate.png',
        category: 'professional',
        hasPhoto: false,
        atsScore: 97,
    },
    {
        id: 'designer',
        name: 'Designer',
        description: 'Creative layout perfect for design professionals',
        thumbnail: '/templates/designer.png',
        category: 'creative',
        hasPhoto: false,
        atsScore: 85,
    },
    {
        id: 'clean',
        name: 'Clean',
        description: 'Ultra-clean design with generous white space',
        thumbnail: '/templates/clean.png',
        category: 'minimal',
        hasPhoto: false,
        atsScore: 98,
    },
];

export function getTemplateById(id: string): ResumeTemplate | undefined {
    return resumeTemplates.find(t => t.id === id);
}
